[tool.poetry]
name = "acestock"
version = "0.1.7"
description = "A gateway for jonpy on A stock market."
authors = ["FangyangJz <fangyang.jing@hotmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
easytrader = "^0.23.0"
jotdx = "^0.1.2"
pandas = "^1.3.4"
tzlocal = "^4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
