[tool.poetry]
name = "posit-playground"
version = "0.1.3"
description = "Posit arithmetic library with no frills"
authors = ["Francesco Urbani <francescourbanidue@gmail.com>"]
readme = "README.md"
repository = "https://github.com/urbanij/posit-playground"
keywords = ["posit", "unum", "posit-arithmetic", "numeric-representation"]

[tool.poetry.dependencies]
python = "^3.6"
softposit = "^0.3.4.4"
pytest = "^6.2.5"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ['py39']
include = '\.pyi?$'
