package:
  name: sports-betting
  version: "0.1.3"

source:
  url: "https://files.pythonhosted.org/packages/ad/50/7e71f102c432798c2b8f2f1c41e05a14362864be49d153a6b30ab596840a/sports-betting-0.1.2.tar.gz"
  sha256: "514431d574ae60297bf7c2233da24266b5a795b6cfb3b44c31d3b701d952666a"

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python
    - pandas >=1.0.0
    - scikit-learn >=1.0.0
    - cloudpickle >=2.0.0
    - beautifulsoup4 >=4.0.0
    - rich >=4.28

  run:
    - python
    - pandas >=1.0.0
    - scikit-learn >=1.0.0
    - cloudpickle >=2.0.0
    - beautifulsoup4 >=4.0.0
    - rich >=4.28

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - sportsbet

about:
  home: "https://github.com/georgedouzas/sports-betting"
  license: "MIT"
  license_file: ""
