# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ho_protocols/live/sensors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ho_protocols/live/sensors.proto',
  package='ho.live.sensors',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fho_protocols/live/sensors.proto\x12\x0fho.live.sensors\"w\n\x0eSensorLiveItem\x12/\n\tbroodnest\x18\x01 \x01(\x0b\x32\x1a.ho.live.sensors.BroodnestH\x00\x12-\n\x08\x65ntrance\x18\x02 \x01(\x0b\x32\x19.ho.live.sensors.EntranceH\x00\x42\x05\n\x03msg\"&\n\tBroodnest\x12\x0c\n\x04temp\x18\x01 \x03(\x02\x12\x0b\n\x03rhl\x18\x02 \x03(\x02\"-\n\x08\x45ntrance\x12\x0f\n\x07\x62\x65\x65s_in\x18\x01 \x01(\x02\x12\x10\n\x08\x62\x65\x65s_out\x18\x02 \x01(\x02\x42\x02H\x03\x62\x06proto3'
)




_SENSORLIVEITEM = _descriptor.Descriptor(
  name='SensorLiveItem',
  full_name='ho.live.sensors.SensorLiveItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='broodnest', full_name='ho.live.sensors.SensorLiveItem.broodnest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entrance', full_name='ho.live.sensors.SensorLiveItem.entrance', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='ho.live.sensors.SensorLiveItem.msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=52,
  serialized_end=171,
)


_BROODNEST = _descriptor.Descriptor(
  name='Broodnest',
  full_name='ho.live.sensors.Broodnest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temp', full_name='ho.live.sensors.Broodnest.temp', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rhl', full_name='ho.live.sensors.Broodnest.rhl', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=211,
)


_ENTRANCE = _descriptor.Descriptor(
  name='Entrance',
  full_name='ho.live.sensors.Entrance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bees_in', full_name='ho.live.sensors.Entrance.bees_in', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bees_out', full_name='ho.live.sensors.Entrance.bees_out', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=258,
)

_SENSORLIVEITEM.fields_by_name['broodnest'].message_type = _BROODNEST
_SENSORLIVEITEM.fields_by_name['entrance'].message_type = _ENTRANCE
_SENSORLIVEITEM.oneofs_by_name['msg'].fields.append(
  _SENSORLIVEITEM.fields_by_name['broodnest'])
_SENSORLIVEITEM.fields_by_name['broodnest'].containing_oneof = _SENSORLIVEITEM.oneofs_by_name['msg']
_SENSORLIVEITEM.oneofs_by_name['msg'].fields.append(
  _SENSORLIVEITEM.fields_by_name['entrance'])
_SENSORLIVEITEM.fields_by_name['entrance'].containing_oneof = _SENSORLIVEITEM.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['SensorLiveItem'] = _SENSORLIVEITEM
DESCRIPTOR.message_types_by_name['Broodnest'] = _BROODNEST
DESCRIPTOR.message_types_by_name['Entrance'] = _ENTRANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorLiveItem = _reflection.GeneratedProtocolMessageType('SensorLiveItem', (_message.Message,), {
  'DESCRIPTOR' : _SENSORLIVEITEM,
  '__module__' : 'ho_protocols.live.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.sensors.SensorLiveItem)
  })
_sym_db.RegisterMessage(SensorLiveItem)

Broodnest = _reflection.GeneratedProtocolMessageType('Broodnest', (_message.Message,), {
  'DESCRIPTOR' : _BROODNEST,
  '__module__' : 'ho_protocols.live.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.sensors.Broodnest)
  })
_sym_db.RegisterMessage(Broodnest)

Entrance = _reflection.GeneratedProtocolMessageType('Entrance', (_message.Message,), {
  'DESCRIPTOR' : _ENTRANCE,
  '__module__' : 'ho_protocols.live.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.sensors.Entrance)
  })
_sym_db.RegisterMessage(Entrance)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
