[tool.poetry]
name = "Lefi"
version = "0.2.4"
license = "MIT"
readme = "README.md"
description = "A discord API wrapper focused on clean code, and usability"
homepage = "https://github.com/an-dyy/Lefi"
documentation = "https://lefi.readthedocs.io/en/latest/"
authors = ["an-dyy <andy.development@protonmail.com>"]
keywords = ["discord", "discordbot", "discordapi"]
packages = [{include = "lefi"}]
include = ["LICENSE"]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.7.4"
PyNaCl = "^1.4.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.7b0"
mypy = "^0.910"
pytest = "^6.2.5"
pre-commit = "^2.15.0"
pytest-asyncio = "^0.15.1"
isort = "^5.9.3"
Sphinx = "^4.3.0"
furo = "^2021.11.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
