[tool.poetry]
name = "koapy"
version = "0.6.2"
description = "Kiwoom Open Api Plus Python"
license = "MIT OR Apache-2.0 OR GPL-3.0-or-later"
authors = ["Yunseong Hwang <kika1492@gmail.com>"]
maintainers = ["Yunseong Hwang <kika1492@gmail.com>"]
readme = "README.rst"
homepage = "https://github.com/elbakramer/koapy"
repository = "https://github.com/elbakramer/koapy"
documentation = "https://koapy.readthedocs.io/en/latest/"
keywords = ["kiwoom", "kiwoom-open-api"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Natural Language :: English",
    "Natural Language :: Korean",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Environment :: Console",
    "Environment :: X11 Applications :: Qt",
    "Topic :: Office/Business :: Financial",
]
include = [
    "docs",
    "tests",
    "*.rst",
    "LICENSE",
    "LICENSE.*",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/elbakramer/koapy/issues"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
click = "^8.0.3"
"discord.py" = "^1.7.3"
exchange-calendars = "^3.5"
grpcio = "^1.42.0"
grpcio-tools = "^1.42.0"
lxml = "^4.7.1"
numpy = "^1.21.4"
openpyxl = "^3.0.9"
pandas = "^1.3.5"
protobuf = "^3.19.1"
pygtrie = "^2.4.2"
pyhocon = "^0.3.59"
PySide2 = "^5.15.2"
pytz = "^2021.3"
QtPy = "^1.11.3"
requests = "^2.26.0"
Rx = "^3.2.0"
schedule = "^1.1.0"
Send2Trash = "^1.8.0"
SQLAlchemy = "^1.4.28"
tabulate = "^0.8.9"
tqdm = "^4.62.3"
tzlocal = "^4.1"
wrapt = "^1.13.3"

# windows dependencies
pywin32 = { version = "^302", markers = "sys_platform == 'win32'" }
pywinauto = { version = "^0.6.8", markers = "sys_platform == 'win32'" }
windows-curses = { version = "^2.3.0", markers = "sys_platform == 'win32'" }

# optional dependencies for backtrader
backtrader = { version = "^1.9.76.123", optional = true }

# optional dependency for Qt binding instead of PySide2
PyQt5 = { version = "^5.15.6", optional = true }

[tool.poetry.extras]
backtrader = ["backtrader"]
PyQt5 = ["PyQt5"]

[tool.poetry.dev-dependencies]
actions-toolkit = "^0.1.7"
black = "^21.12b0"
bump2version = "^1.0.1"
codecov = "^2.1.12"
coverage = "^6.2"
dunamai = "^1.7.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.920"
pip-tools = "^6.4.0"
pre-commit = "^2.16.0"
pylint = "^2.12.2"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-xdist = "^2.5.0"
pyupgrade = "^2.29.1"

Sphinx = "^4.3.1"
sphinx-autoapi = "^1.8.4"
nbconvert = "^6.3.0"
nbsphinx = "^0.8.7"
ipython = "^7.30.1"

[tool.poetry.scripts]
koapy = "koapy.cli:main"

[tool.black]
line-length = 88
force-exclude = "((.+)_pb2.py|(.+)_pb2_grpc.py)"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
