[tool.poetry]
name = "rocktree"
version = "0.1.0"
description = "Rock Solid Library for syncing progress online with byte to byte same working tree."
authors = ["xcodz-dot <71920621+xcodz-dot@users.noreply.github.com>"]
license = "LGPL-2.1-only"
homepage = "https://github.com/xcodz-dot/rocktree"
repository = "https://github.com/xcodz-dot/rocktree"
packages = [
    { include = "rocktree.py", from = 'src' },
    { include = "rocktree_server.py", from = 'src'}
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
patchutils = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
