[tool.poetry]
name = "atolldb"
version = "0.1.0"
description = "Atoll is a project that aim to gather heterogeneous sources of genomic island (GI) sequences and return them in an unified interface."
authors = ["A.Bioteau, N. Cellier"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
numpy = "^1.21.5"
retrying = "^1.3.3"
loguru = "^0.5.3"
beautifulsoup4 = "^4.10.0"
fuzzywuzzy = "^0.18.0"
python-slugify = "^5.0.2"
cachetools = "^4.2.4"
path = "^16.2.0"
peewee = "^3.14.8"
plumbum = "^1.7.1"
attrs = "^21.2.0"
biopython = "^1.79"
more-itertools = "^8.12.0"
tables = "^3.6.1"
lxml = "^4.7.1"
watchdog = "^2.1.6"
requests = "^2.26.0"
tqdm = "^4.62.3"
uplink = "^0.9.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
