__all__ = ['COMMAND_ID', 'OPERATION_ID']

class COMMAND_ID:
    COMMAND_ID_WORKER_INITED = 10001
    COMMAND_ID_UPDATE_GPU_SUMMARY_DONE = 10002
    COMMAND_ID_CLIENT_LAUNCH_TASK = 10003

class OPERATION_ID:
    
    OPERATION_ID_INIT_WORKER = 100001
    OPERATION_ID_UPDATE_GPU_SUMMARY = 100002
    OPERATION_ID_SERVER_LAUNCH_WORKER_TASK = 100003


