from magiccal import *
from magiccal import Data
from magiccal import BMI
from magiccal import Discount
from magiccal import Date
from magiccal import Age
from magiccal import Time
from magiccal import Decimal
from magiccal import Temperature
from magiccal import Speed
from magiccal import Pressure
from magiccal import GST