[tool.poetry]
name = "baseten_scaffolding"
version = "0.0.9"
description = ""
authors = ["Alex Gillmor <alex@baseten.co>"]
include = ["*.txt", "*.Dockerfile", "*.md"]

[tool.poetry.dependencies]
python = ">=3.6.2,<4"
numpy = "^1.18"
msgpack = "1.0.2"
msgpack-numpy = "0.4.7.1"
packaging = "20.9"
kfserving = "^0.3"
python-json-logger = "2.0.2"

[tool.poetry.dev-dependencies]
torch = "^1.9.0"
scikit-learn = "^0.24.2"
ipython = "^7.16"
pytest = "6.2.4"
tensorflow = "2.2"
pandas = "^0.24"
transformers = "^4.11.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
