[tool.poetry]
name = "leveldb-export"
version = "0.1.1"
description = "Package to export documents from LevelDB export (for instance Firestore)."
authors = ["Joël Luijmes <me@joell.dev>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/joelluijmes/leveldb-export"
repository = "https://github.com/joelluijmes/leveldb-export"
keywords = ["firestore", "leveldb", "export", "firestore-export", "leveldb-export"]

[tool.poetry.dependencies]
python = "^3.8"
appengine-python-standard = "^0.3.1"
protobuf = "^3.15.8"
google-crc32c = "^1.1.2"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
