
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-15T18:28:36-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb6fdc500413f9ef40ef8de7cb618374004192f8",
 "version": "2.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
