# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import common_pb2 as common__pb2
from . import imu_pb2 as imu__pb2


class AccelerometerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetAccelerometerMetadata = channel.unary_unary(
                '/mobot.Accelerometer/SetAccelerometerMetadata',
                request_serializer=imu__pb2.SensorMetadata.SerializeToString,
                response_deserializer=common__pb2.Success.FromString,
                )
        self.NewAccelerometerData = channel.unary_unary(
                '/mobot.Accelerometer/NewAccelerometerData',
                request_serializer=common__pb2.Vector3.SerializeToString,
                response_deserializer=common__pb2.Success.FromString,
                )


class AccelerometerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetAccelerometerMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewAccelerometerData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccelerometerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetAccelerometerMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccelerometerMetadata,
                    request_deserializer=imu__pb2.SensorMetadata.FromString,
                    response_serializer=common__pb2.Success.SerializeToString,
            ),
            'NewAccelerometerData': grpc.unary_unary_rpc_method_handler(
                    servicer.NewAccelerometerData,
                    request_deserializer=common__pb2.Vector3.FromString,
                    response_serializer=common__pb2.Success.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mobot.Accelerometer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Accelerometer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetAccelerometerMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mobot.Accelerometer/SetAccelerometerMetadata',
            imu__pb2.SensorMetadata.SerializeToString,
            common__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewAccelerometerData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mobot.Accelerometer/NewAccelerometerData',
            common__pb2.Vector3.SerializeToString,
            common__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)