# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chassis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chassis.proto',
  package='mobot',
  syntax='proto3',
  serialized_options=b'\n\020io.github.mobotxP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rchassis.proto\x12\x05mobot\" \n\x06\x43mdVel\x12\n\n\x02wr\x18\x01 \x01(\x02\x12\n\n\x02wl\x18\x02 \x01(\x02\"~\n\x0f\x43hassisMetadata\x12\x16\n\x0ewheel_diameter\x18\x01 \x01(\x02\x12!\n\x19wheel_to_wheel_separation\x18\x02 \x01(\x02\x12\x17\n\x0fmax_wheel_speed\x18\x03 \x01(\x02\x12\x17\n\x0fmin_wheel_speed\x18\x04 \x01(\x02\x32H\n\x07\x43hassis\x12=\n\x10\x43hassisCmdStream\x12\x16.mobot.ChassisMetadata\x1a\r.mobot.CmdVel\"\x00\x30\x01\x42\x14\n\x10io.github.mobotxP\x01\x62\x06proto3'
)




_CMDVEL = _descriptor.Descriptor(
  name='CmdVel',
  full_name='mobot.CmdVel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wr', full_name='mobot.CmdVel.wr', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wl', full_name='mobot.CmdVel.wl', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=56,
)


_CHASSISMETADATA = _descriptor.Descriptor(
  name='ChassisMetadata',
  full_name='mobot.ChassisMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wheel_diameter', full_name='mobot.ChassisMetadata.wheel_diameter', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wheel_to_wheel_separation', full_name='mobot.ChassisMetadata.wheel_to_wheel_separation', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_wheel_speed', full_name='mobot.ChassisMetadata.max_wheel_speed', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_wheel_speed', full_name='mobot.ChassisMetadata.min_wheel_speed', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=184,
)

DESCRIPTOR.message_types_by_name['CmdVel'] = _CMDVEL
DESCRIPTOR.message_types_by_name['ChassisMetadata'] = _CHASSISMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmdVel = _reflection.GeneratedProtocolMessageType('CmdVel', (_message.Message,), {
  'DESCRIPTOR' : _CMDVEL,
  '__module__' : 'chassis_pb2'
  # @@protoc_insertion_point(class_scope:mobot.CmdVel)
  })
_sym_db.RegisterMessage(CmdVel)

ChassisMetadata = _reflection.GeneratedProtocolMessageType('ChassisMetadata', (_message.Message,), {
  'DESCRIPTOR' : _CHASSISMETADATA,
  '__module__' : 'chassis_pb2'
  # @@protoc_insertion_point(class_scope:mobot.ChassisMetadata)
  })
_sym_db.RegisterMessage(ChassisMetadata)


DESCRIPTOR._options = None

_CHASSIS = _descriptor.ServiceDescriptor(
  name='Chassis',
  full_name='mobot.Chassis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=186,
  serialized_end=258,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChassisCmdStream',
    full_name='mobot.Chassis.ChassisCmdStream',
    index=0,
    containing_service=None,
    input_type=_CHASSISMETADATA,
    output_type=_CMDVEL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHASSIS)

DESCRIPTOR.services_by_name['Chassis'] = _CHASSIS

# @@protoc_insertion_point(module_scope)