build-package:
  stage: build
  image: $CI_REGISTRY_IMAGE/python:latest
  needs:
    job: python-container
  script:
    - make docs
    - python3 -m build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
      - dist/*
  variables:
    GIT_DEPTH: 0