publish-package:
  stage: publish
  image: $CI_REGISTRY_IMAGE/python:latest
  needs:
    job: build-package
  script:
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token
      python3 -m twine upload
      --verbose
      --repository-url "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
      dist/*
