[tool.poetry]
name = "python-AGS4"
version = "0.3.7"
description = "A library to read and write AGS4 files using Pandas DataFrames"
authors = ["Asitha Senanayake <asitha_sena@yahoo.com>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/asitha-sena/python-AGS4"
repository = "https://gitlab.com/ags-data-format-wg/ags-python-library"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0"
openpyxl = "^3.0"
defusedxml = "^0.6"
click = "^7.0"
rich = "^9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
toml = "^0.10"

[tool.poetry.scripts]
ags4_cli = "python_ags4.ags4_cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
