[tool.poetry]
name = "text_alignment_tool"
version = "0.2.15"
description = "A tool for performing complex text alignment processes."
authors = ["Bronson Brown-deVost <bronsonbdevost@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/sofer_mahir/text_alignment_tool"
keywords = ["alignment","needleman", "wunsch", "pipeline"]
packages = [
    { include = "text_alignment_tool" },
]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
swalign = "^0.3.6"
bidict = "^0.21.4"
lxml = "^4.7.1"
dotmap = "^1.3.26"
cursive-re = "^0.0.4"
fuzzywuzzy = "^0.18.0"
minineedle = "^3.0.0"
terminaltables = "^3.1.10"
python-Levenshtein = "^0.12.2"
numpy = "^1.21.4"
pandas = "^1.3.5"
edlib = "^1.3.9"

[tool.poetry.dev-dependencies]
black = {version = "^21.12b0", allow-prereleases = true}
ipykernel = "^6.6.0"
pytest = "^6.2.5"
deepdiff = "^5.6.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
issues = "https://gitlab.com/sofer_mahir/text_alignment_tool/issues"