
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-13T17:14:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5c252734ec7c4cd7519ffb7a913e10688ae76fb",
 "version": "2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
