[tool.poetry]
name = "artsapiclient_ds3478"
version = "0.1.0"
description = "API Client for the Art Institute of Chicago's API which provides JSON formatted data as a REST style service that allows developers to explore and integrate the museum's public data into their projects."
authors = ["Donald Stephens"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.5"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
