
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-16T17:06:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9098ea9caf986017e499c5c8e8eed49d0ff72df5",
 "version": "1.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
