apiVersion: 1
datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb2:8086
    secureJsonData:
      token: ${GRAFANA_INFLUX_DATA_SOURCE_TOKEN}
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: true
      httpMode: POST
    editable: true
