
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-13T19:06:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecf1f7fcb27a5947596f96f2eaff4ec0761ab25c",
 "version": "0.0.59"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
