[tool.poetry]
authors = ["Erica Brandão <erica_martins_brandao@yahoo.com.br>"]
description = "Convert CSV to Json"
name = "erica_csv_converter"
readme = "README.md"
version = "0.1.4"

[tool.poetry.dependencies]
click = "^8.0.3"
pandas = "^1.3.5"
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^4.0.1"
ipython = "^7.30.1"
isort = "^5.10.1"
mypy = "^0.920"
pandas-stubs = "^1.2.0"
pytest = "^5.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry.scripts]
csv_converter = 'erica_csv_converter.converter:converter'

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
