[tool.poetry]
name = "todopyeduP"
version = "0.1.0"
description = "Issue log created by educational purposes"
readme = "README.md"
authors = ["kekbek <vadyusha.surin@gmail.com>"]
packages = [{include = "todopyedu"}]
homepage = "https://gitlab.com/kekbek/python-todo"

[tool.poetry.dependencies]
python = "^3.6"
colorama = "^0.4.4"
shellingham = "^1.4.0"
typer = "^0.4.0"
prettytable = "^2.4.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
todopyeduP = "todopyedu.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


