name: Build and upload to PyPI

env:
    CIBW_SKIP: cp27-* pp27-*
    CIBW_BEFORE_BUILD: python -m pip install setuptools_scm

# Publish when a (published) GitHub Release is created:
on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_dist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install build requirements
        run: python -m pip install build wheel setuptools setuptools_scm
      
      - name: Create distribution
        run: python -m build . --sdist --wheel --outdir dist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/psrqpy*

  upload_pypi:
    needs: [build_dist]
    runs-on: ubuntu-latest
    # Publish when a GitHub Release is created
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: tarball

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
