name: openai/clip-vit-base-patch16
type: clip
description: CLIP model trained by OpenAI
model:
  config: openai/clip-vit-base-patch16
processor:
  config: openai/clip-vit-base-patch16
tokenizer:
  target_lang: en
