[tool.poetry]
name = "plotly-resampler"  # Do not forget to update the __init__.py __version__ variable
version = "0.2.4"
description = "Visualizing large time series with plotly"
authors = ["Jonas Van Der Donckt", "Jeroen Van Der Donckt", "Emiel Deprost"]
readme = "README.md"
repository = "https://github.com/predict-idlab/plotly-resampler"
documentation = "https://predict-idlab.github.io/plotly-resampler"
keywords = ["time-series", "visualization", "resampling", "plotly", "plotly-dash"]

[tool.poetry.dependencies]
python = "^3.7"
jupyter-dash = "^0.4.0"
dash-bootstrap-components = "^0.13.1"
plotly = "^5.3.1"
dash = "^2.0.0"
lttbc = "^0.2.0"
orjson = "^3.6.4"
trace-updater = "^0.0.6"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.2.0"
numpy = "^1.21.2"
pandas = "^1.3.4"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
black = {version = "^21.11b1", allow-prereleases = true}
pdoc3 = "^0.10.0"
selenium = "^4.1.0"
pytest-selenium = "^2.0.1"
fastparquet = "^0.7.2"
webdriver-manager = "^3.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
