[build-system]

requires = [
    "nltk==3.5",
    "scipy==1.5.4",
    "numpy==1.19.4",
    "scikit-learn==0.23.2",
    "pandas==1.1.4",
    "setuptools>=42",
    "wheel",
    "tweet-preprocessor==0.6.0",
    "textblob==0.17.1",
    "regex==2021.11.10",
    "Sastrawi==1.0.1"
]
build-backend = "setuptools.build_meta"