[tool.poetry]
name = "fakts"
version = "0.1.39"
description = "easy configuration discovery based on UDP broadcasts and konfig beacons (servers that redirect configs back to the client)"
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
license = "CC BY-NC 3.0"
packages = [{include = "fakts"}]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.8.2"
koil = "^0.1.58"
PyYAML = ">= 5.2"
QtPy = "^1.11.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-aiohttp = "^0.3.0"
tox = "^3.24.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
