# Generated by Django 3.2.4 on 2021-06-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kelove_database', '0002_alter_ckfinderresource_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ckfinderresource',
            options={'permissions': (('manage_ckfinderresource', '文件管理'),), 'verbose_name': 'Ckfinder 资源', 'verbose_name_plural': 'Ckfinder 资源'},
        ),
    ]
