[tool.poetry]
name = "rocktree"
version = "1.0.0"
description = "Rock Solid Library for syncing progress online with byte to byte same working tree."
authors = ["xcodz-dot <71920621+xcodz-dot@users.noreply.github.com>"]
license = "LGPL-2.1-only"
homepage = "https://github.com/xcodz-dot/rocktree"
repository = "https://github.com/xcodz-dot/rocktree"
packages = [
    { include = "rocktree.py", from = 'src' },
    { include = "rocktree_server.py", from = 'src'}
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
patchutils = "^1.1.3"
flask = { version = "^2.0.2", optional = true }
gevent = { version = ">=21.12.0", optional = true }
requests = "^2.26.0"

[tool.poetry.extras]
server = ["flask"]
server-gevent = ["flask", "gevent"]

[tool.poetry.dev-dependencies]
black = {version = "^21.12b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
