[tool.poetry]
name = "bunumber"
version = "0.0.1"

description = "number by digit and letter"
authors = ["ahamidp <ahamidp@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.2"


[tool.poetry.dev-dependencies]
yapf = "^0.30.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
