[tool.poetry]
name = "littlesis"
version = "0.1.1"
description = "Python wrapper for the LittleSis API."
authors = ["Brendan Mapes"]
license = "MIT"
readme = "README.md"
documentation = 'https://littlesis.readthedocs.io/en/main/'
homepage = "https://github.com/brendanmapes/littlesis"
repository = "https://github.com/brendanmapes/littlesis"

[tool.poetry.dependencies]
python = "^3.9"
ratelimit = "^2.2.1"
requests = "^2.26.0"
pandas = "^1.3.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
myst-nb = "^0.13.1"
sphinx-autoapi = "^1.8.4"
sphinx-rtd-theme = "^1.0.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
