[tool.poetry]
name = "realtime"
version = "0.0.3"
description = ""
authors = ["None"]

[tool.poetry.dependencies]
python = "^3.7"
dataclasses = "^0.6"
websockets = "^9.1"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
