[tool.poetry]
name = "rate"
version = "0.1.1"
description = ""
authors = ["blankalmasry <blankhussien@gmail.com>"]
license = "GPL-3"

[tool.poetry.dependencies]
python = "^3.9"
tqdm = "^4.32"
elote = "^0.1.0"
# elote = {git = "git@github.com:BlankAlmasry/elote.git"}
glicko2 = "2.0.0"
PyInquirer = "1.0.3"
trueskill = "^0.4.5"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# run main.py as rater from the root directory
rate = "rate.main:init"
