[tool.poetry]
name = "mikro-napari"
version = "0.1.41"
description = ""
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
license = "CC BY-NC 3.0"
packages = [{include = "mikro_napari"}]

[tool.poetry.dependencies]
python = "^3.8"
arkitekt = "^0.1.113"
mikro = "^0.1.69"
napari-plugin_engine = "^0.1.4"


[tool.poetry.scripts]
mikro-napari = "mikro_napari.run:main"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-aiohttp = "^0.3.0"
tox = "^3.24.3"

[tool.poetry.plugins."napari.plugin"]
mikro-napari  = "mikro_napari.plugin"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
