[tool.poetry]
name = "aioherepy"
version = "0.1.0"
description = "Asynchronous Python library that provides a simple interface to the HERE APIs."
authors = ["Abdullah Selek <abdullahselek@gmail.com>"]
license = "MIT"

readme = "README.md"

repository = "https://github.com/abdullahselek/aioherepy"
homepage = "https://github.com/abdullahselek/aioherepy"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"


[tool.poetry.dev-dependencies]
aresponses = "2.1.4"
pytest = "6.2.5"
pytest-cov = "3.0.0"
pytest-asyncio = "0.16.0"
pylint = "2.12.2"
codecov = "2.1.12"
black = "21.12b0"
isort = "5.10.1"

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
