# Generated from confusables.txt which had the following header:
    #  confusables.txt
    #  Date: 2021-05-29, 22:09:29 GMT
    #  © 2021 Unicode®, Inc.
    #  Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.
    #  For terms of use, see http://www.unicode.org/terms_of_use.html
    # 
    #  Unicode Security Mechanisms for UTS #39
    #  Version: 14.0.0
    # 
    #  For documentation and usage, see http://www.unicode.org/reports/tr39
    # 


ascii_confusable_map = {
    0x2028: ' ',  # \N{LINE SEPARATOR}
    0x2029: ' ',  # \N{PARAGRAPH SEPARATOR}
    0x1680: ' ',  # \N{OGHAM SPACE MARK}
    0x2000: ' ',  # \N{EN QUAD}
    0x2001: ' ',  # \N{EM QUAD}
    0x2002: ' ',  # \N{EN SPACE}
    0x2003: ' ',  # \N{EM SPACE}
    0x2004: ' ',  # \N{THREE-PER-EM SPACE}
    0x2005: ' ',  # \N{FOUR-PER-EM SPACE}
    0x2006: ' ',  # \N{SIX-PER-EM SPACE}
    0x2008: ' ',  # \N{PUNCTUATION SPACE}
    0x2009: ' ',  # \N{THIN SPACE}
    0x200a: ' ',  # \N{HAIR SPACE}
    0x205f: ' ',  # \N{MEDIUM MATHEMATICAL SPACE}
    0xa0: ' ',  # \N{NO-BREAK SPACE}
    0x2007: ' ',  # \N{FIGURE SPACE}
    0x202f: ' ',  # \N{NARROW NO-BREAK SPACE}
    0x7fa: '_',  # \N{NKO LAJANYALAN}
    0xfe4d: '_',  # \N{DASHED LOW LINE}
    0xfe4e: '_',  # \N{CENTRELINE LOW LINE}
    0xfe4f: '_',  # \N{WAVY LOW LINE}
    0x2010: '-',  # \N{HYPHEN}
    0x2011: '-',  # \N{NON-BREAKING HYPHEN}
    0x2012: '-',  # \N{FIGURE DASH}
    0x2013: '-',  # \N{EN DASH}
    0xfe58: '-',  # \N{SMALL EM DASH}
    0x6d4: '-',  # \N{ARABIC FULL STOP}
    0x2043: '-',  # \N{HYPHEN BULLET}
    0x2d7: '-',  # \N{MODIFIER LETTER MINUS SIGN}
    0x2212: '-',  # \N{MINUS SIGN}
    0x2796: '-',  # \N{HEAVY MINUS SIGN}
    0x2cba: '-',  # \N{COPTIC CAPITAL LETTER DIALECT-P NI}
    0xa4fe: '-.',  # \N{LISU PUNCTUATION COMMA}
    0x60d: ',',  # \N{ARABIC DATE SEPARATOR}
    0x66b: ',',  # \N{ARABIC DECIMAL SEPARATOR}
    0x201a: ',',  # \N{SINGLE LOW-9 QUOTATION MARK}
    0xb8: ',',  # \N{CEDILLA}
    0xa4f9: ',',  # \N{LISU LETTER TONE NA PO}
    0x37e: ';',  # \N{GREEK QUESTION MARK}
    0x903: ':',  # \N{DEVANAGARI SIGN VISARGA}
    0xa83: ':',  # \N{GUJARATI SIGN VISARGA}
    0xff1a: ':',  # \N{FULLWIDTH COLON}
    0x589: ':',  # \N{ARMENIAN FULL STOP}
    0x703: ':',  # \N{SYRIAC SUPRALINEAR COLON}
    0x704: ':',  # \N{SYRIAC SUBLINEAR COLON}
    0x16ec: ':',  # \N{RUNIC MULTIPLE PUNCTUATION}
    0xfe30: ':',  # \N{PRESENTATION FORM FOR VERTICAL TWO DOT LEADER}
    0x1803: ':',  # \N{MONGOLIAN FULL STOP}
    0x1809: ':',  # \N{MONGOLIAN MANCHU FULL STOP}
    0x205a: ':',  # \N{TWO DOT PUNCTUATION}
    0x5c3: ':',  # \N{HEBREW PUNCTUATION SOF PASUQ}
    0x2f8: ':',  # \N{MODIFIER LETTER RAISED COLON}
    0xa789: ':',  # \N{MODIFIER LETTER COLON}
    0x2236: ':',  # \N{RATIO}
    0x2d0: ':',  # \N{MODIFIER LETTER TRIANGULAR COLON}
    0xa4fd: ':',  # \N{LISU LETTER TONE MYA JEU}
    0x2a74: '::=',  # \N{DOUBLE COLON EQUAL}
    0xff01: '!',  # \N{FULLWIDTH EXCLAMATION MARK}
    0x1c3: '!',  # \N{LATIN LETTER RETROFLEX CLICK}
    0x2d51: '!',  # \N{TIFINAGH LETTER TUAREG YANG}
    0x203c: '!!',  # \N{DOUBLE EXCLAMATION MARK}
    0x2049: '!?',  # \N{EXCLAMATION QUESTION MARK}
    0x294: '?',  # \N{LATIN LETTER GLOTTAL STOP}
    0x241: '?',  # \N{LATIN CAPITAL LETTER GLOTTAL STOP}
    0x97d: '?',  # \N{DEVANAGARI LETTER GLOTTAL STOP}
    0x13ae: '?',  # \N{CHEROKEE LETTER HE}
    0xa6eb: '?',  # \N{BAMUM LETTER NTUU}
    0x2048: '?!',  # \N{QUESTION EXCLAMATION MARK}
    0x2047: '??',  # \N{DOUBLE QUESTION MARK}
    0x1d16d: '.',  # \N{MUSICAL SYMBOL COMBINING AUGMENTATION DOT}
    0x2024: '.',  # \N{ONE DOT LEADER}
    0x701: '.',  # \N{SYRIAC SUPRALINEAR FULL STOP}
    0x702: '.',  # \N{SYRIAC SUBLINEAR FULL STOP}
    0xa60e: '.',  # \N{VAI FULL STOP}
    0x10a50: '.',  # \N{KHAROSHTHI PUNCTUATION DOT}
    0x660: '.',  # \N{ARABIC-INDIC DIGIT ZERO}
    0x6f0: '.',  # \N{EXTENDED ARABIC-INDIC DIGIT ZERO}
    0xa4f8: '.',  # \N{LISU LETTER TONE MYA TI}
    0xa4fb: '.,',  # \N{LISU LETTER TONE MYA BO}
    0x2025: '..',  # \N{TWO DOT LEADER}
    0xa4fa: '..',  # \N{LISU LETTER TONE MYA CYA}
    0x2026: '...',  # \N{HORIZONTAL ELLIPSIS}
    0x55d: "'",  # \N{ARMENIAN COMMA}
    0xff07: "'",  # \N{FULLWIDTH APOSTROPHE}
    0x2018: "'",  # \N{LEFT SINGLE QUOTATION MARK}
    0x2019: "'",  # \N{RIGHT SINGLE QUOTATION MARK}
    0x201b: "'",  # \N{SINGLE HIGH-REVERSED-9 QUOTATION MARK}
    0x2032: "'",  # \N{PRIME}
    0x2035: "'",  # \N{REVERSED PRIME}
    0x55a: "'",  # \N{ARMENIAN APOSTROPHE}
    0x5f3: "'",  # \N{HEBREW PUNCTUATION GERESH}
# ignoring: ` -> '
    0x1fef: "'",  # \N{GREEK VARIA}
    0xff40: "'",  # \N{FULLWIDTH GRAVE ACCENT}
    0xb4: "'",  # \N{ACUTE ACCENT}
    0x384: "'",  # \N{GREEK TONOS}
    0x1ffd: "'",  # \N{GREEK OXIA}
    0x1fbd: "'",  # \N{GREEK KORONIS}
    0x1fbf: "'",  # \N{GREEK PSILI}
    0x1ffe: "'",  # \N{GREEK DASIA}
    0x2b9: "'",  # \N{MODIFIER LETTER PRIME}
    0x374: "'",  # \N{GREEK NUMERAL SIGN}
    0x2c8: "'",  # \N{MODIFIER LETTER VERTICAL LINE}
    0x2ca: "'",  # \N{MODIFIER LETTER ACUTE ACCENT}
    0x2cb: "'",  # \N{MODIFIER LETTER GRAVE ACCENT}
    0x2f4: "'",  # \N{MODIFIER LETTER MIDDLE GRAVE ACCENT}
    0x2bb: "'",  # \N{MODIFIER LETTER TURNED COMMA}
    0x2bd: "'",  # \N{MODIFIER LETTER REVERSED COMMA}
    0x2bc: "'",  # \N{MODIFIER LETTER APOSTROPHE}
    0x2be: "'",  # \N{MODIFIER LETTER RIGHT HALF RING}
    0xa78c: "'",  # \N{LATIN SMALL LETTER SALTILLO}
    0x5d9: "'",  # \N{HEBREW LETTER YOD}
    0x7f4: "'",  # \N{NKO HIGH TONE APOSTROPHE}
    0x7f5: "'",  # \N{NKO LOW TONE APOSTROPHE}
    0x144a: "'",  # \N{CANADIAN SYLLABICS WEST-CREE P}
    0x16cc: "'",  # \N{RUNIC LETTER SHORT-TWIG-SOL S}
    0x16f51: "'",  # \N{MIAO SIGN ASPIRATION}
    0x16f52: "'",  # \N{MIAO SIGN REFORMED VOICING}
    0x1cd3: "''",  # \N{VEDIC SIGN NIHSHVASA}
# ignoring: " -> ''
    0xff02: "''",  # \N{FULLWIDTH QUOTATION MARK}
    0x201c: "''",  # \N{LEFT DOUBLE QUOTATION MARK}
    0x201d: "''",  # \N{RIGHT DOUBLE QUOTATION MARK}
    0x201f: "''",  # \N{DOUBLE HIGH-REVERSED-9 QUOTATION MARK}
    0x2033: "''",  # \N{DOUBLE PRIME}
    0x2036: "''",  # \N{REVERSED DOUBLE PRIME}
    0x3003: "''",  # \N{DITTO MARK}
    0x5f4: "''",  # \N{HEBREW PUNCTUATION GERSHAYIM}
    0x2dd: "''",  # \N{DOUBLE ACUTE ACCENT}
    0x2ba: "''",  # \N{MODIFIER LETTER DOUBLE PRIME}
    0x2f6: "''",  # \N{MODIFIER LETTER MIDDLE DOUBLE ACUTE ACCENT}
    0x2ee: "''",  # \N{MODIFIER LETTER DOUBLE APOSTROPHE}
    0x5f2: "''",  # \N{HEBREW LIGATURE YIDDISH DOUBLE YOD}
    0x2034: "'''",  # \N{TRIPLE PRIME}
    0x2037: "'''",  # \N{REVERSED TRIPLE PRIME}
    0x2057: "''''",  # \N{QUADRUPLE PRIME}
    0x181: "'B",  # \N{LATIN CAPITAL LETTER B WITH HOOK}
    0x18a: "'D",  # \N{LATIN CAPITAL LETTER D WITH HOOK}
    0x149: "'n",  # \N{LATIN SMALL LETTER N PRECEDED BY APOSTROPHE}
    0x1a4: "'P",  # \N{LATIN CAPITAL LETTER P WITH HOOK}
    0x1ac: "'T",  # \N{LATIN CAPITAL LETTER T WITH HOOK}
    0x1b3: "'Y",  # \N{LATIN CAPITAL LETTER Y WITH HOOK}
    0xff3b: '(',  # \N{FULLWIDTH LEFT SQUARE BRACKET}
    0x2768: '(',  # \N{MEDIUM LEFT PARENTHESIS ORNAMENT}
    0x2772: '(',  # \N{LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT}
    0x3014: '(',  # \N{LEFT TORTOISE SHELL BRACKET}
    0xfd3e: '(',  # \N{ORNATE LEFT PARENTHESIS}
    0x2e28: '((',  # \N{LEFT DOUBLE PARENTHESIS}
    0x2475: '(2)',  # \N{PARENTHESIZED DIGIT TWO}
    0x2487: '(2O)',  # \N{PARENTHESIZED NUMBER TWENTY}
    0x2476: '(3)',  # \N{PARENTHESIZED DIGIT THREE}
    0x2477: '(4)',  # \N{PARENTHESIZED DIGIT FOUR}
    0x2478: '(5)',  # \N{PARENTHESIZED DIGIT FIVE}
    0x2479: '(6)',  # \N{PARENTHESIZED DIGIT SIX}
    0x247a: '(7)',  # \N{PARENTHESIZED DIGIT SEVEN}
    0x247b: '(8)',  # \N{PARENTHESIZED DIGIT EIGHT}
    0x247c: '(9)',  # \N{PARENTHESIZED DIGIT NINE}
    0x249c: '(a)',  # \N{PARENTHESIZED LATIN SMALL LETTER A}
    0x1f110: '(A)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER A}
    0x249d: '(b)',  # \N{PARENTHESIZED LATIN SMALL LETTER B}
    0x1f111: '(B)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER B}
    0x249e: '(c)',  # \N{PARENTHESIZED LATIN SMALL LETTER C}
    0x1f112: '(C)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER C}
    0x249f: '(d)',  # \N{PARENTHESIZED LATIN SMALL LETTER D}
    0x1f113: '(D)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER D}
    0x24a0: '(e)',  # \N{PARENTHESIZED LATIN SMALL LETTER E}
    0x1f114: '(E)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER E}
    0x24a1: '(f)',  # \N{PARENTHESIZED LATIN SMALL LETTER F}
    0x1f115: '(F)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER F}
    0x24a2: '(g)',  # \N{PARENTHESIZED LATIN SMALL LETTER G}
    0x1f116: '(G)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER G}
    0x24a3: '(h)',  # \N{PARENTHESIZED LATIN SMALL LETTER H}
    0x1f117: '(H)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER H}
    0x24a4: '(i)',  # \N{PARENTHESIZED LATIN SMALL LETTER I}
    0x24a5: '(j)',  # \N{PARENTHESIZED LATIN SMALL LETTER J}
    0x1f119: '(J)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER J}
    0x24a6: '(k)',  # \N{PARENTHESIZED LATIN SMALL LETTER K}
    0x1f11a: '(K)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER K}
    0x2474: '(l)',  # \N{PARENTHESIZED DIGIT ONE}
    0x1f118: '(l)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER I}
    0x24a7: '(l)',  # \N{PARENTHESIZED LATIN SMALL LETTER L}
    0x1f11b: '(L)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER L}
    0x247f: '(l2)',  # \N{PARENTHESIZED NUMBER TWELVE}
    0x2480: '(l3)',  # \N{PARENTHESIZED NUMBER THIRTEEN}
    0x2481: '(l4)',  # \N{PARENTHESIZED NUMBER FOURTEEN}
    0x2482: '(l5)',  # \N{PARENTHESIZED NUMBER FIFTEEN}
    0x2483: '(l6)',  # \N{PARENTHESIZED NUMBER SIXTEEN}
    0x2484: '(l7)',  # \N{PARENTHESIZED NUMBER SEVENTEEN}
    0x2485: '(l8)',  # \N{PARENTHESIZED NUMBER EIGHTEEN}
    0x2486: '(l9)',  # \N{PARENTHESIZED NUMBER NINETEEN}
    0x247e: '(ll)',  # \N{PARENTHESIZED NUMBER ELEVEN}
    0x247d: '(lO)',  # \N{PARENTHESIZED NUMBER TEN}
    0x1f11c: '(M)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER M}
    0x24a9: '(n)',  # \N{PARENTHESIZED LATIN SMALL LETTER N}
    0x1f11d: '(N)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER N}
    0x24aa: '(o)',  # \N{PARENTHESIZED LATIN SMALL LETTER O}
    0x1f11e: '(O)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER O}
    0x24ab: '(p)',  # \N{PARENTHESIZED LATIN SMALL LETTER P}
    0x1f11f: '(P)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER P}
    0x24ac: '(q)',  # \N{PARENTHESIZED LATIN SMALL LETTER Q}
    0x1f120: '(Q)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER Q}
    0x24ad: '(r)',  # \N{PARENTHESIZED LATIN SMALL LETTER R}
    0x1f121: '(R)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER R}
    0x24a8: '(rn)',  # \N{PARENTHESIZED LATIN SMALL LETTER M}
    0x24ae: '(s)',  # \N{PARENTHESIZED LATIN SMALL LETTER S}
    0x1f122: '(S)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER S}
    0x1f12a: '(S)',  # \N{TORTOISE SHELL BRACKETED LATIN CAPITAL LETTER S}
    0x24af: '(t)',  # \N{PARENTHESIZED LATIN SMALL LETTER T}
    0x1f123: '(T)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER T}
    0x24b0: '(u)',  # \N{PARENTHESIZED LATIN SMALL LETTER U}
    0x1f124: '(U)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER U}
    0x24b1: '(v)',  # \N{PARENTHESIZED LATIN SMALL LETTER V}
    0x1f125: '(V)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER V}
    0x24b2: '(w)',  # \N{PARENTHESIZED LATIN SMALL LETTER W}
    0x1f126: '(W)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER W}
    0x24b3: '(x)',  # \N{PARENTHESIZED LATIN SMALL LETTER X}
    0x1f127: '(X)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER X}
    0x24b4: '(y)',  # \N{PARENTHESIZED LATIN SMALL LETTER Y}
    0x1f128: '(Y)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER Y}
    0x24b5: '(z)',  # \N{PARENTHESIZED LATIN SMALL LETTER Z}
    0x1f129: '(Z)',  # \N{PARENTHESIZED LATIN CAPITAL LETTER Z}
    0xff3d: ')',  # \N{FULLWIDTH RIGHT SQUARE BRACKET}
    0x2769: ')',  # \N{MEDIUM RIGHT PARENTHESIS ORNAMENT}
    0x2773: ')',  # \N{LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT}
    0x3015: ')',  # \N{RIGHT TORTOISE SHELL BRACKET}
    0xfd3f: ')',  # \N{ORNATE RIGHT PARENTHESIS}
    0x2e29: '))',  # \N{RIGHT DOUBLE PARENTHESIS}
    0x2774: '{',  # \N{MEDIUM LEFT CURLY BRACKET ORNAMENT}
    0x1d114: '{',  # \N{MUSICAL SYMBOL BRACE}
    0x2775: '}',  # \N{MEDIUM RIGHT CURLY BRACKET ORNAMENT}
    0x204e: '*',  # \N{LOW ASTERISK}
    0x66d: '*',  # \N{ARABIC FIVE POINTED STAR}
    0x2217: '*',  # \N{ASTERISK OPERATOR}
    0x1031f: '*',  # \N{OLD ITALIC LETTER ESS}
    0x1735: '/',  # \N{PHILIPPINE SINGLE PUNCTUATION}
    0x2041: '/',  # \N{CARET INSERTION POINT}
    0x2215: '/',  # \N{DIVISION SLASH}
    0x2044: '/',  # \N{FRACTION SLASH}
    0x2571: '/',  # \N{BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT}
    0x27cb: '/',  # \N{MATHEMATICAL RISING DIAGONAL}
    0x29f8: '/',  # \N{BIG SOLIDUS}
    0x1d23a: '/',  # \N{GREEK INSTRUMENTAL NOTATION SYMBOL-47}
    0x31d3: '/',  # \N{CJK STROKE SP}
    0x3033: '/',  # \N{VERTICAL KANA REPEAT MARK UPPER HALF}
    0x2cc6: '/',  # \N{COPTIC CAPITAL LETTER OLD COPTIC ESH}
    0x30ce: '/',  # \N{KATAKANA LETTER NO}
    0x4e3f: '/',  # \N{CJK UNIFIED IDEOGRAPH-4E3F}
    0x2f03: '/',  # \N{KANGXI RADICAL SLASH}
    0x2afd: '//',  # \N{DOUBLE SOLIDUS OPERATOR}
    0x2afb: '///',  # \N{TRIPLE SOLIDUS BINARY RELATION}
    0xff3c: '\\',  # \N{FULLWIDTH REVERSE SOLIDUS}
    0xfe68: '\\',  # \N{SMALL REVERSE SOLIDUS}
    0x2216: '\\',  # \N{SET MINUS}
    0x27cd: '\\',  # \N{MATHEMATICAL FALLING DIAGONAL}
    0x29f5: '\\',  # \N{REVERSE SOLIDUS OPERATOR}
    0x29f9: '\\',  # \N{BIG REVERSE SOLIDUS}
    0x1d20f: '\\',  # \N{GREEK VOCAL NOTATION SYMBOL-16}
    0x1d23b: '\\',  # \N{GREEK INSTRUMENTAL NOTATION SYMBOL-48}
    0x31d4: '\\',  # \N{CJK STROKE D}
    0x4e36: '\\',  # \N{CJK UNIFIED IDEOGRAPH-4E36}
    0x2f02: '\\',  # \N{KANGXI RADICAL DOT}
    0x2cf9: '\\\\',  # \N{COPTIC OLD NUBIAN FULL STOP}
    0x244a: '\\\\',  # \N{OCR DOUBLE BACKSLASH}
    0xa778: '&',  # \N{LATIN SMALL LETTER UM}
    0x2c4: '^',  # \N{MODIFIER LETTER UP ARROWHEAD}
    0x2c6: '^',  # \N{MODIFIER LETTER CIRCUMFLEX ACCENT}
    0x16ed: '+',  # \N{RUNIC CROSS PUNCTUATION}
    0x2795: '+',  # \N{HEAVY PLUS SIGN}
    0x1029b: '+',  # \N{LYCIAN LETTER H}
    0x2039: '<',  # \N{SINGLE LEFT-POINTING ANGLE QUOTATION MARK}
    0x276e: '<',  # \N{HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT}
    0x2c2: '<',  # \N{MODIFIER LETTER LEFT ARROWHEAD}
    0x1d236: '<',  # \N{GREEK INSTRUMENTAL NOTATION SYMBOL-40}
    0x1438: '<',  # \N{CANADIAN SYLLABICS PA}
    0x16b2: '<',  # \N{RUNIC LETTER KAUNA}
    0x226a: '<<',  # \N{MUCH LESS-THAN}
    0x22d8: '<<<',  # \N{VERY MUCH LESS-THAN}
    0x1400: '=',  # \N{CANADIAN SYLLABICS HYPHEN}
    0x2e40: '=',  # \N{DOUBLE HYPHEN}
    0x30a0: '=',  # \N{KATAKANA-HIRAGANA DOUBLE HYPHEN}
    0xa4ff: '=',  # \N{LISU PUNCTUATION FULL STOP}
    0x2a75: '==',  # \N{TWO CONSECUTIVE EQUALS SIGNS}
    0x2a76: '===',  # \N{THREE CONSECUTIVE EQUALS SIGNS}
    0x203a: '>',  # \N{SINGLE RIGHT-POINTING ANGLE QUOTATION MARK}
    0x276f: '>',  # \N{HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT}
    0x2c3: '>',  # \N{MODIFIER LETTER RIGHT ARROWHEAD}
    0x1d237: '>',  # \N{GREEK INSTRUMENTAL NOTATION SYMBOL-42}
    0x1433: '>',  # \N{CANADIAN SYLLABICS PO}
    0x16f3f: '>',  # \N{MIAO LETTER ARCHAIC ZZA}
    0x2aa5: '><',  # \N{GREATER-THAN BESIDE LESS-THAN}
    0x226b: '>>',  # \N{MUCH GREATER-THAN}
    0x2a20: '>>',  # \N{Z NOTATION SCHEMA PIPING}
    0x22d9: '>>>',  # \N{VERY MUCH GREATER-THAN}
    0x2053: '~',  # \N{SWUNG DASH}
    0x2dc: '~',  # \N{SMALL TILDE}
    0x1fc0: '~',  # \N{GREEK PERISPOMENI}
    0x223c: '~',  # \N{TILDE OPERATOR}
    0x1d7d0: '2',  # \N{MATHEMATICAL BOLD DIGIT TWO}
    0x1d7da: '2',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT TWO}
    0x1d7e4: '2',  # \N{MATHEMATICAL SANS-SERIF DIGIT TWO}
    0x1d7ee: '2',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT TWO}
    0x1d7f8: '2',  # \N{MATHEMATICAL MONOSPACE DIGIT TWO}
    0x1fbf2: '2',  # \N{SEGMENTED DIGIT TWO}
    0xa75a: '2',  # \N{LATIN CAPITAL LETTER R ROTUNDA}
    0x1a7: '2',  # \N{LATIN CAPITAL LETTER TONE TWO}
    0x3e8: '2',  # \N{COPTIC CAPITAL LETTER HORI}
    0xa644: '2',  # \N{CYRILLIC CAPITAL LETTER REVERSED DZE}
    0x14bf: '2',  # \N{CANADIAN SYLLABICS SAYISI M}
    0xa6ef: '2',  # \N{BAMUM LETTER KOGHOM}
    0x1f103: '2,',  # \N{DIGIT TWO COMMA}
    0x2489: '2.',  # \N{DIGIT TWO FULL STOP}
    0x249b: '2O.',  # \N{NUMBER TWENTY FULL STOP}
    0x1d206: '3',  # \N{GREEK VOCAL NOTATION SYMBOL-7}
    0x1d7d1: '3',  # \N{MATHEMATICAL BOLD DIGIT THREE}
    0x1d7db: '3',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT THREE}
    0x1d7e5: '3',  # \N{MATHEMATICAL SANS-SERIF DIGIT THREE}
    0x1d7ef: '3',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT THREE}
    0x1d7f9: '3',  # \N{MATHEMATICAL MONOSPACE DIGIT THREE}
    0x1fbf3: '3',  # \N{SEGMENTED DIGIT THREE}
    0xa7ab: '3',  # \N{LATIN CAPITAL LETTER REVERSED OPEN E}
    0x21c: '3',  # \N{LATIN CAPITAL LETTER YOGH}
    0x1b7: '3',  # \N{LATIN CAPITAL LETTER EZH}
    0xa76a: '3',  # \N{LATIN CAPITAL LETTER ET}
    0x2ccc: '3',  # \N{COPTIC CAPITAL LETTER OLD COPTIC HORI}
    0x417: '3',  # \N{CYRILLIC CAPITAL LETTER ZE}
    0x4e0: '3',  # \N{CYRILLIC CAPITAL LETTER ABKHASIAN DZE}
    0x16f3b: '3',  # \N{MIAO LETTER ZA}
    0x118ca: '3',  # \N{WARANG CITI SMALL LETTER ANG}
    0x1f104: '3,',  # \N{DIGIT THREE COMMA}
    0x248a: '3.',  # \N{DIGIT THREE FULL STOP}
    0x1d7d2: '4',  # \N{MATHEMATICAL BOLD DIGIT FOUR}
    0x1d7dc: '4',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT FOUR}
    0x1d7e6: '4',  # \N{MATHEMATICAL SANS-SERIF DIGIT FOUR}
    0x1d7f0: '4',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT FOUR}
    0x1d7fa: '4',  # \N{MATHEMATICAL MONOSPACE DIGIT FOUR}
    0x1fbf4: '4',  # \N{SEGMENTED DIGIT FOUR}
    0x13ce: '4',  # \N{CHEROKEE LETTER SE}
    0x118af: '4',  # \N{WARANG CITI CAPITAL LETTER UC}
    0x1f105: '4,',  # \N{DIGIT FOUR COMMA}
    0x248b: '4.',  # \N{DIGIT FOUR FULL STOP}
    0x1d7d3: '5',  # \N{MATHEMATICAL BOLD DIGIT FIVE}
    0x1d7dd: '5',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT FIVE}
    0x1d7e7: '5',  # \N{MATHEMATICAL SANS-SERIF DIGIT FIVE}
    0x1d7f1: '5',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT FIVE}
    0x1d7fb: '5',  # \N{MATHEMATICAL MONOSPACE DIGIT FIVE}
    0x1fbf5: '5',  # \N{SEGMENTED DIGIT FIVE}
    0x1bc: '5',  # \N{LATIN CAPITAL LETTER TONE FIVE}
    0x118bb: '5',  # \N{WARANG CITI CAPITAL LETTER HORR}
    0x1f106: '5,',  # \N{DIGIT FIVE COMMA}
    0x248c: '5.',  # \N{DIGIT FIVE FULL STOP}
    0x1d7d4: '6',  # \N{MATHEMATICAL BOLD DIGIT SIX}
    0x1d7de: '6',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT SIX}
    0x1d7e8: '6',  # \N{MATHEMATICAL SANS-SERIF DIGIT SIX}
    0x1d7f2: '6',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT SIX}
    0x1d7fc: '6',  # \N{MATHEMATICAL MONOSPACE DIGIT SIX}
    0x1fbf6: '6',  # \N{SEGMENTED DIGIT SIX}
    0x2cd2: '6',  # \N{COPTIC CAPITAL LETTER OLD COPTIC HEI}
    0x431: '6',  # \N{CYRILLIC SMALL LETTER BE}
    0x13ee: '6',  # \N{CHEROKEE LETTER WV}
    0x118d5: '6',  # \N{WARANG CITI SMALL LETTER AT}
    0x1f107: '6,',  # \N{DIGIT SIX COMMA}
    0x248d: '6.',  # \N{DIGIT SIX FULL STOP}
    0x1d212: '7',  # \N{GREEK VOCAL NOTATION SYMBOL-19}
    0x1d7d5: '7',  # \N{MATHEMATICAL BOLD DIGIT SEVEN}
    0x1d7df: '7',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT SEVEN}
    0x1d7e9: '7',  # \N{MATHEMATICAL SANS-SERIF DIGIT SEVEN}
    0x1d7f3: '7',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT SEVEN}
    0x1d7fd: '7',  # \N{MATHEMATICAL MONOSPACE DIGIT SEVEN}
    0x1fbf7: '7',  # \N{SEGMENTED DIGIT SEVEN}
    0x104d2: '7',  # \N{OSAGE CAPITAL LETTER ZA}
    0x118c6: '7',  # \N{WARANG CITI SMALL LETTER II}
    0x1f108: '7,',  # \N{DIGIT SEVEN COMMA}
    0x248e: '7.',  # \N{DIGIT SEVEN FULL STOP}
    0xb03: '8',  # \N{ORIYA SIGN VISARGA}
    0x9ea: '8',  # \N{BENGALI DIGIT FOUR}
    0xa6a: '8',  # \N{GURMUKHI DIGIT FOUR}
    0x1e8cb: '8',  # \N{MENDE KIKAKUI DIGIT FIVE}
    0x1d7d6: '8',  # \N{MATHEMATICAL BOLD DIGIT EIGHT}
    0x1d7e0: '8',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT EIGHT}
    0x1d7ea: '8',  # \N{MATHEMATICAL SANS-SERIF DIGIT EIGHT}
    0x1d7f4: '8',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT EIGHT}
    0x1d7fe: '8',  # \N{MATHEMATICAL MONOSPACE DIGIT EIGHT}
    0x1fbf8: '8',  # \N{SEGMENTED DIGIT EIGHT}
    0x223: '8',  # \N{LATIN SMALL LETTER OU}
    0x222: '8',  # \N{LATIN CAPITAL LETTER OU}
    0x1031a: '8',  # \N{OLD ITALIC LETTER EF}
    0x1f109: '8,',  # \N{DIGIT EIGHT COMMA}
    0x248f: '8.',  # \N{DIGIT EIGHT FULL STOP}
    0xa67: '9',  # \N{GURMUKHI DIGIT ONE}
    0xb68: '9',  # \N{ORIYA DIGIT TWO}
    0x9ed: '9',  # \N{BENGALI DIGIT SEVEN}
    0xd6d: '9',  # \N{MALAYALAM DIGIT SEVEN}
    0x1d7d7: '9',  # \N{MATHEMATICAL BOLD DIGIT NINE}
    0x1d7e1: '9',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT NINE}
    0x1d7eb: '9',  # \N{MATHEMATICAL SANS-SERIF DIGIT NINE}
    0x1d7f5: '9',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT NINE}
    0x1d7ff: '9',  # \N{MATHEMATICAL MONOSPACE DIGIT NINE}
    0x1fbf9: '9',  # \N{SEGMENTED DIGIT NINE}
    0xa76e: '9',  # \N{LATIN CAPITAL LETTER CON}
    0x2cca: '9',  # \N{COPTIC CAPITAL LETTER DIALECT-P HORI}
    0x118cc: '9',  # \N{WARANG CITI SMALL LETTER KO}
    0x118ac: '9',  # \N{WARANG CITI CAPITAL LETTER KO}
    0x118d6: '9',  # \N{WARANG CITI SMALL LETTER AM}
    0x1f10a: '9,',  # \N{DIGIT NINE COMMA}
    0x2490: '9.',  # \N{DIGIT NINE FULL STOP}
    0x237a: 'a',  # \N{APL FUNCTIONAL SYMBOL ALPHA}
    0xff41: 'a',  # \N{FULLWIDTH LATIN SMALL LETTER A}
    0x1d41a: 'a',  # \N{MATHEMATICAL BOLD SMALL A}
    0x1d44e: 'a',  # \N{MATHEMATICAL ITALIC SMALL A}
    0x1d482: 'a',  # \N{MATHEMATICAL BOLD ITALIC SMALL A}
    0x1d4b6: 'a',  # \N{MATHEMATICAL SCRIPT SMALL A}
    0x1d4ea: 'a',  # \N{MATHEMATICAL BOLD SCRIPT SMALL A}
    0x1d51e: 'a',  # \N{MATHEMATICAL FRAKTUR SMALL A}
    0x1d552: 'a',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL A}
    0x1d586: 'a',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL A}
    0x1d5ba: 'a',  # \N{MATHEMATICAL SANS-SERIF SMALL A}
    0x1d5ee: 'a',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL A}
    0x1d622: 'a',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL A}
    0x1d656: 'a',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL A}
    0x1d68a: 'a',  # \N{MATHEMATICAL MONOSPACE SMALL A}
    0x251: 'a',  # \N{LATIN SMALL LETTER ALPHA}
    0x3b1: 'a',  # \N{GREEK SMALL LETTER ALPHA}
    0x1d6c2: 'a',  # \N{MATHEMATICAL BOLD SMALL ALPHA}
    0x1d6fc: 'a',  # \N{MATHEMATICAL ITALIC SMALL ALPHA}
    0x1d736: 'a',  # \N{MATHEMATICAL BOLD ITALIC SMALL ALPHA}
    0x1d770: 'a',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL ALPHA}
    0x1d7aa: 'a',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ALPHA}
    0x430: 'a',  # \N{CYRILLIC SMALL LETTER A}
    0xff21: 'A',  # \N{FULLWIDTH LATIN CAPITAL LETTER A}
    0x1d400: 'A',  # \N{MATHEMATICAL BOLD CAPITAL A}
    0x1d434: 'A',  # \N{MATHEMATICAL ITALIC CAPITAL A}
    0x1d468: 'A',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL A}
    0x1d49c: 'A',  # \N{MATHEMATICAL SCRIPT CAPITAL A}
    0x1d4d0: 'A',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL A}
    0x1d504: 'A',  # \N{MATHEMATICAL FRAKTUR CAPITAL A}
    0x1d538: 'A',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL A}
    0x1d56c: 'A',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL A}
    0x1d5a0: 'A',  # \N{MATHEMATICAL SANS-SERIF CAPITAL A}
    0x1d5d4: 'A',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL A}
    0x1d608: 'A',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL A}
    0x1d63c: 'A',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL A}
    0x1d670: 'A',  # \N{MATHEMATICAL MONOSPACE CAPITAL A}
    0x391: 'A',  # \N{GREEK CAPITAL LETTER ALPHA}
    0x1d6a8: 'A',  # \N{MATHEMATICAL BOLD CAPITAL ALPHA}
    0x1d6e2: 'A',  # \N{MATHEMATICAL ITALIC CAPITAL ALPHA}
    0x1d71c: 'A',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL ALPHA}
    0x1d756: 'A',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL ALPHA}
    0x1d790: 'A',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ALPHA}
    0x410: 'A',  # \N{CYRILLIC CAPITAL LETTER A}
    0x13aa: 'A',  # \N{CHEROKEE LETTER GO}
    0x15c5: 'A',  # \N{CANADIAN SYLLABICS CARRIER GHO}
    0xa4ee: 'A',  # \N{LISU LETTER A}
    0x16f40: 'A',  # \N{MIAO LETTER ZZYA}
    0x102a0: 'A',  # \N{CARIAN LETTER A}
    0x2100: 'a/c',  # \N{ACCOUNT OF}
    0x2101: 'a/s',  # \N{ADDRESSED TO THE SUBJECT}
    0xa733: 'aa',  # \N{LATIN SMALL LETTER AA}
    0xa732: 'AA',  # \N{LATIN CAPITAL LETTER AA}
    0xe6: 'ae',  # \N{LATIN SMALL LETTER AE}
    0x4d5: 'ae',  # \N{CYRILLIC SMALL LIGATURE A IE}
    0xc6: 'AE',  # \N{LATIN CAPITAL LETTER AE}
    0x4d4: 'AE',  # \N{CYRILLIC CAPITAL LIGATURE A IE}
    0xa735: 'ao',  # \N{LATIN SMALL LETTER AO}
    0xa734: 'AO',  # \N{LATIN CAPITAL LETTER AO}
    0x1f707: 'AR',  # \N{ALCHEMICAL SYMBOL FOR AQUA REGIA-2}
    0xa737: 'au',  # \N{LATIN SMALL LETTER AU}
    0xa736: 'AU',  # \N{LATIN CAPITAL LETTER AU}
    0xa739: 'av',  # \N{LATIN SMALL LETTER AV}
    0xa73b: 'av',  # \N{LATIN SMALL LETTER AV WITH HORIZONTAL BAR}
    0xa738: 'AV',  # \N{LATIN CAPITAL LETTER AV}
    0xa73a: 'AV',  # \N{LATIN CAPITAL LETTER AV WITH HORIZONTAL BAR}
    0xa73d: 'ay',  # \N{LATIN SMALL LETTER AY}
    0xa73c: 'AY',  # \N{LATIN CAPITAL LETTER AY}
    0x1d41b: 'b',  # \N{MATHEMATICAL BOLD SMALL B}
    0x1d44f: 'b',  # \N{MATHEMATICAL ITALIC SMALL B}
    0x1d483: 'b',  # \N{MATHEMATICAL BOLD ITALIC SMALL B}
    0x1d4b7: 'b',  # \N{MATHEMATICAL SCRIPT SMALL B}
    0x1d4eb: 'b',  # \N{MATHEMATICAL BOLD SCRIPT SMALL B}
    0x1d51f: 'b',  # \N{MATHEMATICAL FRAKTUR SMALL B}
    0x1d553: 'b',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL B}
    0x1d587: 'b',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL B}
    0x1d5bb: 'b',  # \N{MATHEMATICAL SANS-SERIF SMALL B}
    0x1d5ef: 'b',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL B}
    0x1d623: 'b',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL B}
    0x1d657: 'b',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL B}
    0x1d68b: 'b',  # \N{MATHEMATICAL MONOSPACE SMALL B}
    0x184: 'b',  # \N{LATIN CAPITAL LETTER TONE SIX}
    0x42c: 'b',  # \N{CYRILLIC CAPITAL LETTER SOFT SIGN}
    0x13cf: 'b',  # \N{CHEROKEE LETTER SI}
    0x1472: 'b',  # \N{CANADIAN SYLLABICS KA}
    0x15af: 'b',  # \N{CANADIAN SYLLABICS AIVILIK B}
    0xff22: 'B',  # \N{FULLWIDTH LATIN CAPITAL LETTER B}
    0x212c: 'B',  # \N{SCRIPT CAPITAL B}
    0x1d401: 'B',  # \N{MATHEMATICAL BOLD CAPITAL B}
    0x1d435: 'B',  # \N{MATHEMATICAL ITALIC CAPITAL B}
    0x1d469: 'B',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL B}
    0x1d4d1: 'B',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL B}
    0x1d505: 'B',  # \N{MATHEMATICAL FRAKTUR CAPITAL B}
    0x1d539: 'B',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL B}
    0x1d56d: 'B',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL B}
    0x1d5a1: 'B',  # \N{MATHEMATICAL SANS-SERIF CAPITAL B}
    0x1d5d5: 'B',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL B}
    0x1d609: 'B',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL B}
    0x1d63d: 'B',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL B}
    0x1d671: 'B',  # \N{MATHEMATICAL MONOSPACE CAPITAL B}
    0xa7b4: 'B',  # \N{LATIN CAPITAL LETTER BETA}
    0x392: 'B',  # \N{GREEK CAPITAL LETTER BETA}
    0x1d6a9: 'B',  # \N{MATHEMATICAL BOLD CAPITAL BETA}
    0x1d6e3: 'B',  # \N{MATHEMATICAL ITALIC CAPITAL BETA}
    0x1d71d: 'B',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL BETA}
    0x1d757: 'B',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL BETA}
    0x1d791: 'B',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL BETA}
    0x412: 'B',  # \N{CYRILLIC CAPITAL LETTER VE}
    0x13f4: 'B',  # \N{CHEROKEE LETTER YV}
    0x15f7: 'B',  # \N{CANADIAN SYLLABICS CARRIER KHE}
    0xa4d0: 'B',  # \N{LISU LETTER BA}
    0x10282: 'B',  # \N{LYCIAN LETTER B}
    0x102a1: 'B',  # \N{CARIAN LETTER P2}
    0x10301: 'B',  # \N{OLD ITALIC LETTER BE}
    0x1488: "b'",  # \N{CANADIAN SYLLABICS SOUTH-SLAVEY KAH}
    0x42b: 'bl',  # \N{CYRILLIC CAPITAL LETTER YERU}
    0xff43: 'c',  # \N{FULLWIDTH LATIN SMALL LETTER C}
    0x217d: 'c',  # \N{SMALL ROMAN NUMERAL ONE HUNDRED}
    0x1d41c: 'c',  # \N{MATHEMATICAL BOLD SMALL C}
    0x1d450: 'c',  # \N{MATHEMATICAL ITALIC SMALL C}
    0x1d484: 'c',  # \N{MATHEMATICAL BOLD ITALIC SMALL C}
    0x1d4b8: 'c',  # \N{MATHEMATICAL SCRIPT SMALL C}
    0x1d4ec: 'c',  # \N{MATHEMATICAL BOLD SCRIPT SMALL C}
    0x1d520: 'c',  # \N{MATHEMATICAL FRAKTUR SMALL C}
    0x1d554: 'c',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL C}
    0x1d588: 'c',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL C}
    0x1d5bc: 'c',  # \N{MATHEMATICAL SANS-SERIF SMALL C}
    0x1d5f0: 'c',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL C}
    0x1d624: 'c',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL C}
    0x1d658: 'c',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL C}
    0x1d68c: 'c',  # \N{MATHEMATICAL MONOSPACE SMALL C}
    0x1d04: 'c',  # \N{LATIN LETTER SMALL CAPITAL C}
    0x3f2: 'c',  # \N{GREEK LUNATE SIGMA SYMBOL}
    0x2ca5: 'c',  # \N{COPTIC SMALL LETTER SIMA}
    0x441: 'c',  # \N{CYRILLIC SMALL LETTER ES}
    0xabaf: 'c',  # \N{CHEROKEE SMALL LETTER TLI}
    0x1043d: 'c',  # \N{DESERET SMALL LETTER CHEE}
    0x1f74c: 'C',  # \N{ALCHEMICAL SYMBOL FOR CALX}
    0x118f2: 'C',  # \N{WARANG CITI NUMBER NINETY}
    0x118e9: 'C',  # \N{WARANG CITI DIGIT NINE}
    0xff23: 'C',  # \N{FULLWIDTH LATIN CAPITAL LETTER C}
    0x216d: 'C',  # \N{ROMAN NUMERAL ONE HUNDRED}
    0x2102: 'C',  # \N{DOUBLE-STRUCK CAPITAL C}
    0x212d: 'C',  # \N{BLACK-LETTER CAPITAL C}
    0x1d402: 'C',  # \N{MATHEMATICAL BOLD CAPITAL C}
    0x1d436: 'C',  # \N{MATHEMATICAL ITALIC CAPITAL C}
    0x1d46a: 'C',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL C}
    0x1d49e: 'C',  # \N{MATHEMATICAL SCRIPT CAPITAL C}
    0x1d4d2: 'C',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL C}
    0x1d56e: 'C',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL C}
    0x1d5a2: 'C',  # \N{MATHEMATICAL SANS-SERIF CAPITAL C}
    0x1d5d6: 'C',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL C}
    0x1d60a: 'C',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL C}
    0x1d63e: 'C',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL C}
    0x1d672: 'C',  # \N{MATHEMATICAL MONOSPACE CAPITAL C}
    0x3f9: 'C',  # \N{GREEK CAPITAL LUNATE SIGMA SYMBOL}
    0x2ca4: 'C',  # \N{COPTIC CAPITAL LETTER SIMA}
    0x421: 'C',  # \N{CYRILLIC CAPITAL LETTER ES}
    0x13df: 'C',  # \N{CHEROKEE LETTER TLI}
    0xa4da: 'C',  # \N{LISU LETTER CA}
    0x102a2: 'C',  # \N{CARIAN LETTER D}
    0x10302: 'C',  # \N{OLD ITALIC LETTER KE}
    0x10415: 'C',  # \N{DESERET CAPITAL LETTER CHEE}
    0x1051c: 'C',  # \N{ELBASAN LETTER SHE}
    0x187: "C'",  # \N{LATIN CAPITAL LETTER C WITH HOOK}
    0x2105: 'c/o',  # \N{CARE OF}
    0x2106: 'c/u',  # \N{CADA UNA}
    0x217e: 'd',  # \N{SMALL ROMAN NUMERAL FIVE HUNDRED}
    0x2146: 'd',  # \N{DOUBLE-STRUCK ITALIC SMALL D}
    0x1d41d: 'd',  # \N{MATHEMATICAL BOLD SMALL D}
    0x1d451: 'd',  # \N{MATHEMATICAL ITALIC SMALL D}
    0x1d485: 'd',  # \N{MATHEMATICAL BOLD ITALIC SMALL D}
    0x1d4b9: 'd',  # \N{MATHEMATICAL SCRIPT SMALL D}
    0x1d4ed: 'd',  # \N{MATHEMATICAL BOLD SCRIPT SMALL D}
    0x1d521: 'd',  # \N{MATHEMATICAL FRAKTUR SMALL D}
    0x1d555: 'd',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL D}
    0x1d589: 'd',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL D}
    0x1d5bd: 'd',  # \N{MATHEMATICAL SANS-SERIF SMALL D}
    0x1d5f1: 'd',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL D}
    0x1d625: 'd',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL D}
    0x1d659: 'd',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL D}
    0x1d68d: 'd',  # \N{MATHEMATICAL MONOSPACE SMALL D}
    0x501: 'd',  # \N{CYRILLIC SMALL LETTER KOMI DE}
    0x13e7: 'd',  # \N{CHEROKEE LETTER TSU}
    0x146f: 'd',  # \N{CANADIAN SYLLABICS KO}
    0xa4d2: 'd',  # \N{LISU LETTER PHA}
    0x216e: 'D',  # \N{ROMAN NUMERAL FIVE HUNDRED}
    0x2145: 'D',  # \N{DOUBLE-STRUCK ITALIC CAPITAL D}
    0x1d403: 'D',  # \N{MATHEMATICAL BOLD CAPITAL D}
    0x1d437: 'D',  # \N{MATHEMATICAL ITALIC CAPITAL D}
    0x1d46b: 'D',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL D}
    0x1d49f: 'D',  # \N{MATHEMATICAL SCRIPT CAPITAL D}
    0x1d4d3: 'D',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL D}
    0x1d507: 'D',  # \N{MATHEMATICAL FRAKTUR CAPITAL D}
    0x1d53b: 'D',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL D}
    0x1d56f: 'D',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL D}
    0x1d5a3: 'D',  # \N{MATHEMATICAL SANS-SERIF CAPITAL D}
    0x1d5d7: 'D',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL D}
    0x1d60b: 'D',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL D}
    0x1d63f: 'D',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL D}
    0x1d673: 'D',  # \N{MATHEMATICAL MONOSPACE CAPITAL D}
    0x13a0: 'D',  # \N{CHEROKEE LETTER A}
    0x15de: 'D',  # \N{CANADIAN SYLLABICS CARRIER THE}
    0x15ea: 'D',  # \N{CANADIAN SYLLABICS CARRIER PE}
    0xa4d3: 'D',  # \N{LISU LETTER DA}
    0x1487: "d'",  # \N{CANADIAN SYLLABICS SOUTH-SLAVEY KOH}
    0x1f3: 'dz',  # \N{LATIN SMALL LETTER DZ}
    0x2a3: 'dz',  # \N{LATIN SMALL LETTER DZ DIGRAPH}
    0x1f2: 'Dz',  # \N{LATIN CAPITAL LETTER D WITH SMALL LETTER Z}
    0x1f1: 'DZ',  # \N{LATIN CAPITAL LETTER DZ}
    0x212e: 'e',  # \N{ESTIMATED SYMBOL}
    0xff45: 'e',  # \N{FULLWIDTH LATIN SMALL LETTER E}
    0x212f: 'e',  # \N{SCRIPT SMALL E}
    0x2147: 'e',  # \N{DOUBLE-STRUCK ITALIC SMALL E}
    0x1d41e: 'e',  # \N{MATHEMATICAL BOLD SMALL E}
    0x1d452: 'e',  # \N{MATHEMATICAL ITALIC SMALL E}
    0x1d486: 'e',  # \N{MATHEMATICAL BOLD ITALIC SMALL E}
    0x1d4ee: 'e',  # \N{MATHEMATICAL BOLD SCRIPT SMALL E}
    0x1d522: 'e',  # \N{MATHEMATICAL FRAKTUR SMALL E}
    0x1d556: 'e',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL E}
    0x1d58a: 'e',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL E}
    0x1d5be: 'e',  # \N{MATHEMATICAL SANS-SERIF SMALL E}
    0x1d5f2: 'e',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL E}
    0x1d626: 'e',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL E}
    0x1d65a: 'e',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL E}
    0x1d68e: 'e',  # \N{MATHEMATICAL MONOSPACE SMALL E}
    0xab32: 'e',  # \N{LATIN SMALL LETTER BLACKLETTER E}
    0x435: 'e',  # \N{CYRILLIC SMALL LETTER IE}
    0x4bd: 'e',  # \N{CYRILLIC SMALL LETTER ABKHASIAN CHE}
    0x22ff: 'E',  # \N{Z NOTATION BAG MEMBERSHIP}
    0xff25: 'E',  # \N{FULLWIDTH LATIN CAPITAL LETTER E}
    0x2130: 'E',  # \N{SCRIPT CAPITAL E}
    0x1d404: 'E',  # \N{MATHEMATICAL BOLD CAPITAL E}
    0x1d438: 'E',  # \N{MATHEMATICAL ITALIC CAPITAL E}
    0x1d46c: 'E',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL E}
    0x1d4d4: 'E',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL E}
    0x1d508: 'E',  # \N{MATHEMATICAL FRAKTUR CAPITAL E}
    0x1d53c: 'E',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL E}
    0x1d570: 'E',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL E}
    0x1d5a4: 'E',  # \N{MATHEMATICAL SANS-SERIF CAPITAL E}
    0x1d5d8: 'E',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL E}
    0x1d60c: 'E',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL E}
    0x1d640: 'E',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL E}
    0x1d674: 'E',  # \N{MATHEMATICAL MONOSPACE CAPITAL E}
    0x395: 'E',  # \N{GREEK CAPITAL LETTER EPSILON}
    0x1d6ac: 'E',  # \N{MATHEMATICAL BOLD CAPITAL EPSILON}
    0x1d6e6: 'E',  # \N{MATHEMATICAL ITALIC CAPITAL EPSILON}
    0x1d720: 'E',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL EPSILON}
    0x1d75a: 'E',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL EPSILON}
    0x1d794: 'E',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL EPSILON}
    0x415: 'E',  # \N{CYRILLIC CAPITAL LETTER IE}
    0x2d39: 'E',  # \N{TIFINAGH LETTER YADD}
    0x13ac: 'E',  # \N{CHEROKEE LETTER GV}
    0xa4f0: 'E',  # \N{LISU LETTER E}
    0x118a6: 'E',  # \N{WARANG CITI CAPITAL LETTER II}
    0x118ae: 'E',  # \N{WARANG CITI CAPITAL LETTER YUJ}
    0x10286: 'E',  # \N{LYCIAN LETTER I}
    0x1d41f: 'f',  # \N{MATHEMATICAL BOLD SMALL F}
    0x1d453: 'f',  # \N{MATHEMATICAL ITALIC SMALL F}
    0x1d487: 'f',  # \N{MATHEMATICAL BOLD ITALIC SMALL F}
    0x1d4bb: 'f',  # \N{MATHEMATICAL SCRIPT SMALL F}
    0x1d4ef: 'f',  # \N{MATHEMATICAL BOLD SCRIPT SMALL F}
    0x1d523: 'f',  # \N{MATHEMATICAL FRAKTUR SMALL F}
    0x1d557: 'f',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL F}
    0x1d58b: 'f',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL F}
    0x1d5bf: 'f',  # \N{MATHEMATICAL SANS-SERIF SMALL F}
    0x1d5f3: 'f',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL F}
    0x1d627: 'f',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL F}
    0x1d65b: 'f',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL F}
    0x1d68f: 'f',  # \N{MATHEMATICAL MONOSPACE SMALL F}
    0xab35: 'f',  # \N{LATIN SMALL LETTER LENIS F}
    0xa799: 'f',  # \N{LATIN SMALL LETTER F WITH STROKE}
    0x17f: 'f',  # \N{LATIN SMALL LETTER LONG S}
    0x1e9d: 'f',  # \N{LATIN SMALL LETTER LONG S WITH HIGH STROKE}
    0x584: 'f',  # \N{ARMENIAN SMALL LETTER KEH}
    0x1d213: 'F',  # \N{GREEK VOCAL NOTATION SYMBOL-20}
    0x2131: 'F',  # \N{SCRIPT CAPITAL F}
    0x1d405: 'F',  # \N{MATHEMATICAL BOLD CAPITAL F}
    0x1d439: 'F',  # \N{MATHEMATICAL ITALIC CAPITAL F}
    0x1d46d: 'F',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL F}
    0x1d4d5: 'F',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL F}
    0x1d509: 'F',  # \N{MATHEMATICAL FRAKTUR CAPITAL F}
    0x1d53d: 'F',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL F}
    0x1d571: 'F',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL F}
    0x1d5a5: 'F',  # \N{MATHEMATICAL SANS-SERIF CAPITAL F}
    0x1d5d9: 'F',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL F}
    0x1d60d: 'F',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL F}
    0x1d641: 'F',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL F}
    0x1d675: 'F',  # \N{MATHEMATICAL MONOSPACE CAPITAL F}
    0xa798: 'F',  # \N{LATIN CAPITAL LETTER F WITH STROKE}
    0x3dc: 'F',  # \N{GREEK LETTER DIGAMMA}
    0x1d7ca: 'F',  # \N{MATHEMATICAL BOLD CAPITAL DIGAMMA}
    0x15b4: 'F',  # \N{CANADIAN SYLLABICS BLACKFOOT WE}
    0xa4dd: 'F',  # \N{LISU LETTER TSA}
    0x118c2: 'F',  # \N{WARANG CITI SMALL LETTER WI}
    0x118a2: 'F',  # \N{WARANG CITI CAPITAL LETTER WI}
    0x10287: 'F',  # \N{LYCIAN LETTER W}
    0x102a5: 'F',  # \N{CARIAN LETTER R}
    0x10525: 'F',  # \N{ELBASAN LETTER GHE}
    0x213b: 'FAX',  # \N{FACSIMILE SIGN}
    0xfb00: 'ff',  # \N{LATIN SMALL LIGATURE FF}
    0xfb03: 'ffi',  # \N{LATIN SMALL LIGATURE FFI}
    0xfb04: 'ffl',  # \N{LATIN SMALL LIGATURE FFL}
    0xfb01: 'fi',  # \N{LATIN SMALL LIGATURE FI}
    0xfb02: 'fl',  # \N{LATIN SMALL LIGATURE FL}
    0xff47: 'g',  # \N{FULLWIDTH LATIN SMALL LETTER G}
    0x210a: 'g',  # \N{SCRIPT SMALL G}
    0x1d420: 'g',  # \N{MATHEMATICAL BOLD SMALL G}
    0x1d454: 'g',  # \N{MATHEMATICAL ITALIC SMALL G}
    0x1d488: 'g',  # \N{MATHEMATICAL BOLD ITALIC SMALL G}
    0x1d4f0: 'g',  # \N{MATHEMATICAL BOLD SCRIPT SMALL G}
    0x1d524: 'g',  # \N{MATHEMATICAL FRAKTUR SMALL G}
    0x1d558: 'g',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL G}
    0x1d58c: 'g',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL G}
    0x1d5c0: 'g',  # \N{MATHEMATICAL SANS-SERIF SMALL G}
    0x1d5f4: 'g',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL G}
    0x1d628: 'g',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL G}
    0x1d65c: 'g',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL G}
    0x1d690: 'g',  # \N{MATHEMATICAL MONOSPACE SMALL G}
    0x261: 'g',  # \N{LATIN SMALL LETTER SCRIPT G}
    0x1d83: 'g',  # \N{LATIN SMALL LETTER G WITH PALATAL HOOK}
    0x18d: 'g',  # \N{LATIN SMALL LETTER TURNED DELTA}
    0x581: 'g',  # \N{ARMENIAN SMALL LETTER CO}
    0x1d406: 'G',  # \N{MATHEMATICAL BOLD CAPITAL G}
    0x1d43a: 'G',  # \N{MATHEMATICAL ITALIC CAPITAL G}
    0x1d46e: 'G',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL G}
    0x1d4a2: 'G',  # \N{MATHEMATICAL SCRIPT CAPITAL G}
    0x1d4d6: 'G',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL G}
    0x1d50a: 'G',  # \N{MATHEMATICAL FRAKTUR CAPITAL G}
    0x1d53e: 'G',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL G}
    0x1d572: 'G',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL G}
    0x1d5a6: 'G',  # \N{MATHEMATICAL SANS-SERIF CAPITAL G}
    0x1d5da: 'G',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL G}
    0x1d60e: 'G',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL G}
    0x1d642: 'G',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL G}
    0x1d676: 'G',  # \N{MATHEMATICAL MONOSPACE CAPITAL G}
    0x50c: 'G',  # \N{CYRILLIC CAPITAL LETTER KOMI SJE}
    0x13c0: 'G',  # \N{CHEROKEE LETTER NAH}
    0x13f3: 'G',  # \N{CHEROKEE LETTER YU}
    0xa4d6: 'G',  # \N{LISU LETTER GA}
    0x193: "G'",  # \N{LATIN CAPITAL LETTER G WITH HOOK}
    0xff48: 'h',  # \N{FULLWIDTH LATIN SMALL LETTER H}
    0x210e: 'h',  # \N{PLANCK CONSTANT}
    0x1d421: 'h',  # \N{MATHEMATICAL BOLD SMALL H}
    0x1d489: 'h',  # \N{MATHEMATICAL BOLD ITALIC SMALL H}
    0x1d4bd: 'h',  # \N{MATHEMATICAL SCRIPT SMALL H}
    0x1d4f1: 'h',  # \N{MATHEMATICAL BOLD SCRIPT SMALL H}
    0x1d525: 'h',  # \N{MATHEMATICAL FRAKTUR SMALL H}
    0x1d559: 'h',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL H}
    0x1d58d: 'h',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL H}
    0x1d5c1: 'h',  # \N{MATHEMATICAL SANS-SERIF SMALL H}
    0x1d5f5: 'h',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL H}
    0x1d629: 'h',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL H}
    0x1d65d: 'h',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL H}
    0x1d691: 'h',  # \N{MATHEMATICAL MONOSPACE SMALL H}
    0x4bb: 'h',  # \N{CYRILLIC SMALL LETTER SHHA}
    0x570: 'h',  # \N{ARMENIAN SMALL LETTER HO}
    0x13c2: 'h',  # \N{CHEROKEE LETTER NI}
    0xff28: 'H',  # \N{FULLWIDTH LATIN CAPITAL LETTER H}
    0x210b: 'H',  # \N{SCRIPT CAPITAL H}
    0x210c: 'H',  # \N{BLACK-LETTER CAPITAL H}
    0x210d: 'H',  # \N{DOUBLE-STRUCK CAPITAL H}
    0x1d407: 'H',  # \N{MATHEMATICAL BOLD CAPITAL H}
    0x1d43b: 'H',  # \N{MATHEMATICAL ITALIC CAPITAL H}
    0x1d46f: 'H',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL H}
    0x1d4d7: 'H',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL H}
    0x1d573: 'H',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL H}
    0x1d5a7: 'H',  # \N{MATHEMATICAL SANS-SERIF CAPITAL H}
    0x1d5db: 'H',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL H}
    0x1d60f: 'H',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL H}
    0x1d643: 'H',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL H}
    0x1d677: 'H',  # \N{MATHEMATICAL MONOSPACE CAPITAL H}
    0x397: 'H',  # \N{GREEK CAPITAL LETTER ETA}
    0x1d6ae: 'H',  # \N{MATHEMATICAL BOLD CAPITAL ETA}
    0x1d6e8: 'H',  # \N{MATHEMATICAL ITALIC CAPITAL ETA}
    0x1d722: 'H',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL ETA}
    0x1d75c: 'H',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL ETA}
    0x1d796: 'H',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ETA}
    0x2c8e: 'H',  # \N{COPTIC CAPITAL LETTER HATE}
    0x41d: 'H',  # \N{CYRILLIC CAPITAL LETTER EN}
    0x13bb: 'H',  # \N{CHEROKEE LETTER MI}
    0x157c: 'H',  # \N{CANADIAN SYLLABICS NUNAVUT H}
    0xa4e7: 'H',  # \N{LISU LETTER XA}
    0x102cf: 'H',  # \N{CARIAN LETTER E2}
    0x2db: 'i',  # \N{OGONEK}
    0x2373: 'i',  # \N{APL FUNCTIONAL SYMBOL IOTA}
    0xff49: 'i',  # \N{FULLWIDTH LATIN SMALL LETTER I}
    0x2170: 'i',  # \N{SMALL ROMAN NUMERAL ONE}
    0x2139: 'i',  # \N{INFORMATION SOURCE}
    0x2148: 'i',  # \N{DOUBLE-STRUCK ITALIC SMALL I}
    0x1d422: 'i',  # \N{MATHEMATICAL BOLD SMALL I}
    0x1d456: 'i',  # \N{MATHEMATICAL ITALIC SMALL I}
    0x1d48a: 'i',  # \N{MATHEMATICAL BOLD ITALIC SMALL I}
    0x1d4be: 'i',  # \N{MATHEMATICAL SCRIPT SMALL I}
    0x1d4f2: 'i',  # \N{MATHEMATICAL BOLD SCRIPT SMALL I}
    0x1d526: 'i',  # \N{MATHEMATICAL FRAKTUR SMALL I}
    0x1d55a: 'i',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL I}
    0x1d58e: 'i',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL I}
    0x1d5c2: 'i',  # \N{MATHEMATICAL SANS-SERIF SMALL I}
    0x1d5f6: 'i',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL I}
    0x1d62a: 'i',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL I}
    0x1d65e: 'i',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL I}
    0x1d692: 'i',  # \N{MATHEMATICAL MONOSPACE SMALL I}
    0x131: 'i',  # \N{LATIN SMALL LETTER DOTLESS I}
    0x1d6a4: 'i',  # \N{MATHEMATICAL ITALIC SMALL DOTLESS I}
    0x26a: 'i',  # \N{LATIN LETTER SMALL CAPITAL I}
    0x269: 'i',  # \N{LATIN SMALL LETTER IOTA}
    0x3b9: 'i',  # \N{GREEK SMALL LETTER IOTA}
    0x1fbe: 'i',  # \N{GREEK PROSGEGRAMMENI}
    0x37a: 'i',  # \N{GREEK YPOGEGRAMMENI}
    0x1d6ca: 'i',  # \N{MATHEMATICAL BOLD SMALL IOTA}
    0x1d704: 'i',  # \N{MATHEMATICAL ITALIC SMALL IOTA}
    0x1d73e: 'i',  # \N{MATHEMATICAL BOLD ITALIC SMALL IOTA}
    0x1d778: 'i',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL IOTA}
    0x1d7b2: 'i',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL IOTA}
    0x456: 'i',  # \N{CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I}
    0xa647: 'i',  # \N{CYRILLIC SMALL LETTER IOTA}
    0x4cf: 'i',  # \N{CYRILLIC SMALL LETTER PALOCHKA}
    0xab75: 'i',  # \N{CHEROKEE SMALL LETTER V}
    0x13a5: 'i',  # \N{CHEROKEE LETTER V}
    0x118c3: 'i',  # \N{WARANG CITI SMALL LETTER YU}
    0x2171: 'ii',  # \N{SMALL ROMAN NUMERAL TWO}
    0x2172: 'iii',  # \N{SMALL ROMAN NUMERAL THREE}
    0x133: 'ij',  # \N{LATIN SMALL LIGATURE IJ}
    0x2173: 'iv',  # \N{SMALL ROMAN NUMERAL FOUR}
    0x2178: 'ix',  # \N{SMALL ROMAN NUMERAL NINE}
    0xff4a: 'j',  # \N{FULLWIDTH LATIN SMALL LETTER J}
    0x2149: 'j',  # \N{DOUBLE-STRUCK ITALIC SMALL J}
    0x1d423: 'j',  # \N{MATHEMATICAL BOLD SMALL J}
    0x1d457: 'j',  # \N{MATHEMATICAL ITALIC SMALL J}
    0x1d48b: 'j',  # \N{MATHEMATICAL BOLD ITALIC SMALL J}
    0x1d4bf: 'j',  # \N{MATHEMATICAL SCRIPT SMALL J}
    0x1d4f3: 'j',  # \N{MATHEMATICAL BOLD SCRIPT SMALL J}
    0x1d527: 'j',  # \N{MATHEMATICAL FRAKTUR SMALL J}
    0x1d55b: 'j',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL J}
    0x1d58f: 'j',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL J}
    0x1d5c3: 'j',  # \N{MATHEMATICAL SANS-SERIF SMALL J}
    0x1d5f7: 'j',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL J}
    0x1d62b: 'j',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL J}
    0x1d65f: 'j',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL J}
    0x1d693: 'j',  # \N{MATHEMATICAL MONOSPACE SMALL J}
    0x3f3: 'j',  # \N{GREEK LETTER YOT}
    0x458: 'j',  # \N{CYRILLIC SMALL LETTER JE}
    0xff2a: 'J',  # \N{FULLWIDTH LATIN CAPITAL LETTER J}
    0x1d409: 'J',  # \N{MATHEMATICAL BOLD CAPITAL J}
    0x1d43d: 'J',  # \N{MATHEMATICAL ITALIC CAPITAL J}
    0x1d471: 'J',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL J}
    0x1d4a5: 'J',  # \N{MATHEMATICAL SCRIPT CAPITAL J}
    0x1d4d9: 'J',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL J}
    0x1d50d: 'J',  # \N{MATHEMATICAL FRAKTUR CAPITAL J}
    0x1d541: 'J',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL J}
    0x1d575: 'J',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL J}
    0x1d5a9: 'J',  # \N{MATHEMATICAL SANS-SERIF CAPITAL J}
    0x1d5dd: 'J',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL J}
    0x1d611: 'J',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL J}
    0x1d645: 'J',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL J}
    0x1d679: 'J',  # \N{MATHEMATICAL MONOSPACE CAPITAL J}
    0xa7b2: 'J',  # \N{LATIN CAPITAL LETTER J WITH CROSSED-TAIL}
    0x37f: 'J',  # \N{GREEK CAPITAL LETTER YOT}
    0x408: 'J',  # \N{CYRILLIC CAPITAL LETTER JE}
    0x13ab: 'J',  # \N{CHEROKEE LETTER GU}
    0x148d: 'J',  # \N{CANADIAN SYLLABICS CO}
    0xa4d9: 'J',  # \N{LISU LETTER JA}
    0x1d424: 'k',  # \N{MATHEMATICAL BOLD SMALL K}
    0x1d458: 'k',  # \N{MATHEMATICAL ITALIC SMALL K}
    0x1d48c: 'k',  # \N{MATHEMATICAL BOLD ITALIC SMALL K}
    0x1d4c0: 'k',  # \N{MATHEMATICAL SCRIPT SMALL K}
    0x1d4f4: 'k',  # \N{MATHEMATICAL BOLD SCRIPT SMALL K}
    0x1d528: 'k',  # \N{MATHEMATICAL FRAKTUR SMALL K}
    0x1d55c: 'k',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL K}
    0x1d590: 'k',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL K}
    0x1d5c4: 'k',  # \N{MATHEMATICAL SANS-SERIF SMALL K}
    0x1d5f8: 'k',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL K}
    0x1d62c: 'k',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL K}
    0x1d660: 'k',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL K}
    0x1d694: 'k',  # \N{MATHEMATICAL MONOSPACE SMALL K}
    0x212a: 'K',  # \N{KELVIN SIGN}
    0xff2b: 'K',  # \N{FULLWIDTH LATIN CAPITAL LETTER K}
    0x1d40a: 'K',  # \N{MATHEMATICAL BOLD CAPITAL K}
    0x1d43e: 'K',  # \N{MATHEMATICAL ITALIC CAPITAL K}
    0x1d472: 'K',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL K}
    0x1d4a6: 'K',  # \N{MATHEMATICAL SCRIPT CAPITAL K}
    0x1d4da: 'K',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL K}
    0x1d50e: 'K',  # \N{MATHEMATICAL FRAKTUR CAPITAL K}
    0x1d542: 'K',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL K}
    0x1d576: 'K',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL K}
    0x1d5aa: 'K',  # \N{MATHEMATICAL SANS-SERIF CAPITAL K}
    0x1d5de: 'K',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL K}
    0x1d612: 'K',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL K}
    0x1d646: 'K',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL K}
    0x1d67a: 'K',  # \N{MATHEMATICAL MONOSPACE CAPITAL K}
    0x39a: 'K',  # \N{GREEK CAPITAL LETTER KAPPA}
    0x1d6b1: 'K',  # \N{MATHEMATICAL BOLD CAPITAL KAPPA}
    0x1d6eb: 'K',  # \N{MATHEMATICAL ITALIC CAPITAL KAPPA}
    0x1d725: 'K',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL KAPPA}
    0x1d75f: 'K',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL KAPPA}
    0x1d799: 'K',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL KAPPA}
    0x2c94: 'K',  # \N{COPTIC CAPITAL LETTER KAPA}
    0x41a: 'K',  # \N{CYRILLIC CAPITAL LETTER KA}
    0x13e6: 'K',  # \N{CHEROKEE LETTER TSO}
    0x16d5: 'K',  # \N{RUNIC LETTER OPEN-P}
    0xa4d7: 'K',  # \N{LISU LETTER KA}
    0x10518: 'K',  # \N{ELBASAN LETTER QE}
    0x198: "K'",  # \N{LATIN CAPITAL LETTER K WITH HOOK}
    0x5c0: 'l',  # \N{HEBREW PUNCTUATION PASEQ}
# ignoring: | -> l
    0x2223: 'l',  # \N{DIVIDES}
    0x23fd: 'l',  # \N{POWER ON SYMBOL}
    0xffe8: 'l',  # \N{HALFWIDTH FORMS LIGHT VERTICAL}
# ignoring: 1 -> l
    0x661: 'l',  # \N{ARABIC-INDIC DIGIT ONE}
    0x6f1: 'l',  # \N{EXTENDED ARABIC-INDIC DIGIT ONE}
    0x10320: 'l',  # \N{OLD ITALIC NUMERAL ONE}
    0x1e8c7: 'l',  # \N{MENDE KIKAKUI DIGIT ONE}
    0x1d7cf: 'l',  # \N{MATHEMATICAL BOLD DIGIT ONE}
    0x1d7d9: 'l',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT ONE}
    0x1d7e3: 'l',  # \N{MATHEMATICAL SANS-SERIF DIGIT ONE}
    0x1d7ed: 'l',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT ONE}
    0x1d7f7: 'l',  # \N{MATHEMATICAL MONOSPACE DIGIT ONE}
    0x1fbf1: 'l',  # \N{SEGMENTED DIGIT ONE}
# ignoring: I -> l
    0xff29: 'l',  # \N{FULLWIDTH LATIN CAPITAL LETTER I}
    0x2160: 'l',  # \N{ROMAN NUMERAL ONE}
    0x2110: 'l',  # \N{SCRIPT CAPITAL I}
    0x2111: 'l',  # \N{BLACK-LETTER CAPITAL I}
    0x1d408: 'l',  # \N{MATHEMATICAL BOLD CAPITAL I}
    0x1d43c: 'l',  # \N{MATHEMATICAL ITALIC CAPITAL I}
    0x1d470: 'l',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL I}
    0x1d4d8: 'l',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL I}
    0x1d540: 'l',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL I}
    0x1d574: 'l',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL I}
    0x1d5a8: 'l',  # \N{MATHEMATICAL SANS-SERIF CAPITAL I}
    0x1d5dc: 'l',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL I}
    0x1d610: 'l',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL I}
    0x1d644: 'l',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL I}
    0x1d678: 'l',  # \N{MATHEMATICAL MONOSPACE CAPITAL I}
    0x196: 'l',  # \N{LATIN CAPITAL LETTER IOTA}
    0xff4c: 'l',  # \N{FULLWIDTH LATIN SMALL LETTER L}
    0x217c: 'l',  # \N{SMALL ROMAN NUMERAL FIFTY}
    0x2113: 'l',  # \N{SCRIPT SMALL L}
    0x1d425: 'l',  # \N{MATHEMATICAL BOLD SMALL L}
    0x1d459: 'l',  # \N{MATHEMATICAL ITALIC SMALL L}
    0x1d48d: 'l',  # \N{MATHEMATICAL BOLD ITALIC SMALL L}
    0x1d4c1: 'l',  # \N{MATHEMATICAL SCRIPT SMALL L}
    0x1d4f5: 'l',  # \N{MATHEMATICAL BOLD SCRIPT SMALL L}
    0x1d529: 'l',  # \N{MATHEMATICAL FRAKTUR SMALL L}
    0x1d55d: 'l',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL L}
    0x1d591: 'l',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL L}
    0x1d5c5: 'l',  # \N{MATHEMATICAL SANS-SERIF SMALL L}
    0x1d5f9: 'l',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL L}
    0x1d62d: 'l',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL L}
    0x1d661: 'l',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL L}
    0x1d695: 'l',  # \N{MATHEMATICAL MONOSPACE SMALL L}
    0x1c0: 'l',  # \N{LATIN LETTER DENTAL CLICK}
    0x399: 'l',  # \N{GREEK CAPITAL LETTER IOTA}
    0x1d6b0: 'l',  # \N{MATHEMATICAL BOLD CAPITAL IOTA}
    0x1d6ea: 'l',  # \N{MATHEMATICAL ITALIC CAPITAL IOTA}
    0x1d724: 'l',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL IOTA}
    0x1d75e: 'l',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL IOTA}
    0x1d798: 'l',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL IOTA}
    0x2c92: 'l',  # \N{COPTIC CAPITAL LETTER IAUDA}
    0x406: 'l',  # \N{CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I}
    0x4c0: 'l',  # \N{CYRILLIC LETTER PALOCHKA}
    0x5d5: 'l',  # \N{HEBREW LETTER VAV}
    0x5df: 'l',  # \N{HEBREW LETTER FINAL NUN}
    0x627: 'l',  # \N{ARABIC LETTER ALEF}
    0x1ee00: 'l',  # \N{ARABIC MATHEMATICAL ALEF}
    0x1ee80: 'l',  # \N{ARABIC MATHEMATICAL LOOPED ALEF}
    0xfe8e: 'l',  # \N{ARABIC LETTER ALEF FINAL FORM}
    0xfe8d: 'l',  # \N{ARABIC LETTER ALEF ISOLATED FORM}
    0x7ca: 'l',  # \N{NKO LETTER A}
    0x2d4f: 'l',  # \N{TIFINAGH LETTER YAN}
    0x16c1: 'l',  # \N{RUNIC LETTER ISAZ IS ISS I}
    0xa4f2: 'l',  # \N{LISU LETTER I}
    0x16f28: 'l',  # \N{MIAO LETTER GHA}
    0x1028a: 'l',  # \N{LYCIAN LETTER J}
    0x10309: 'l',  # \N{OLD ITALIC LETTER I}
    0x1d22a: 'L',  # \N{GREEK INSTRUMENTAL NOTATION SYMBOL-23}
    0x216c: 'L',  # \N{ROMAN NUMERAL FIFTY}
    0x2112: 'L',  # \N{SCRIPT CAPITAL L}
    0x1d40b: 'L',  # \N{MATHEMATICAL BOLD CAPITAL L}
    0x1d43f: 'L',  # \N{MATHEMATICAL ITALIC CAPITAL L}
    0x1d473: 'L',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL L}
    0x1d4db: 'L',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL L}
    0x1d50f: 'L',  # \N{MATHEMATICAL FRAKTUR CAPITAL L}
    0x1d543: 'L',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL L}
    0x1d577: 'L',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL L}
    0x1d5ab: 'L',  # \N{MATHEMATICAL SANS-SERIF CAPITAL L}
    0x1d5df: 'L',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL L}
    0x1d613: 'L',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL L}
    0x1d647: 'L',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL L}
    0x1d67b: 'L',  # \N{MATHEMATICAL MONOSPACE CAPITAL L}
    0x2cd0: 'L',  # \N{COPTIC CAPITAL LETTER L-SHAPED HA}
    0x13de: 'L',  # \N{CHEROKEE LETTER TLE}
    0x14aa: 'L',  # \N{CANADIAN SYLLABICS MA}
    0xa4e1: 'L',  # \N{LISU LETTER LA}
    0x16f16: 'L',  # \N{MIAO LETTER LA}
    0x118a3: 'L',  # \N{WARANG CITI CAPITAL LETTER YU}
    0x118b2: 'L',  # \N{WARANG CITI CAPITAL LETTER TTE}
    0x1041b: 'L',  # \N{DESERET CAPITAL LETTER ETH}
    0x10526: 'L',  # \N{ELBASAN LETTER GHAMMA}
    0x1f102: 'l,',  # \N{DIGIT ONE COMMA}
    0x2488: 'l.',  # \N{DIGIT ONE FULL STOP}
    0x5f1: "l'",  # \N{HEBREW LIGATURE YIDDISH VAV YOD}
    0x2493: 'l2.',  # \N{NUMBER TWELVE FULL STOP}
    0x2494: 'l3.',  # \N{NUMBER THIRTEEN FULL STOP}
    0x2495: 'l4.',  # \N{NUMBER FOURTEEN FULL STOP}
    0x2496: 'l5.',  # \N{NUMBER FIFTEEN FULL STOP}
    0x2497: 'l6.',  # \N{NUMBER SIXTEEN FULL STOP}
    0x2498: 'l7.',  # \N{NUMBER SEVENTEEN FULL STOP}
    0x2499: 'l8.',  # \N{NUMBER EIGHTEEN FULL STOP}
    0x249a: 'l9.',  # \N{NUMBER NINETEEN FULL STOP}
    0x1c9: 'lj',  # \N{LATIN SMALL LETTER LJ}
    0x132: 'lJ',  # \N{LATIN CAPITAL LIGATURE IJ}
    0x1c8: 'Lj',  # \N{LATIN CAPITAL LETTER L WITH SMALL LETTER J}
    0x1c7: 'LJ',  # \N{LATIN CAPITAL LETTER LJ}
    0x2016: 'll',  # \N{DOUBLE VERTICAL LINE}
    0x2225: 'll',  # \N{PARALLEL TO}
    0x2161: 'll',  # \N{ROMAN NUMERAL TWO}
    0x1c1: 'll',  # \N{LATIN LETTER LATERAL CLICK}
    0x5f0: 'll',  # \N{HEBREW LIGATURE YIDDISH DOUBLE VAV}
    0x2492: 'll.',  # \N{NUMBER ELEVEN FULL STOP}
    0x2162: 'lll',  # \N{ROMAN NUMERAL THREE}
    0x42e: 'lO',  # \N{CYRILLIC CAPITAL LETTER YU}
    0x2491: 'lO.',  # \N{NUMBER TEN FULL STOP}
    0x2aa: 'ls',  # \N{LATIN SMALL LETTER LS DIGRAPH}
    0x20b6: 'lt',  # \N{LIVRE TOURNOIS SIGN}
    0x2163: 'lV',  # \N{ROMAN NUMERAL FOUR}
    0x2168: 'lX',  # \N{ROMAN NUMERAL NINE}
    0x2ab: 'lz',  # \N{LATIN SMALL LETTER LZ DIGRAPH}
    0xff2d: 'M',  # \N{FULLWIDTH LATIN CAPITAL LETTER M}
    0x216f: 'M',  # \N{ROMAN NUMERAL ONE THOUSAND}
    0x2133: 'M',  # \N{SCRIPT CAPITAL M}
    0x1d40c: 'M',  # \N{MATHEMATICAL BOLD CAPITAL M}
    0x1d440: 'M',  # \N{MATHEMATICAL ITALIC CAPITAL M}
    0x1d474: 'M',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL M}
    0x1d4dc: 'M',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL M}
    0x1d510: 'M',  # \N{MATHEMATICAL FRAKTUR CAPITAL M}
    0x1d544: 'M',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL M}
    0x1d578: 'M',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL M}
    0x1d5ac: 'M',  # \N{MATHEMATICAL SANS-SERIF CAPITAL M}
    0x1d5e0: 'M',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL M}
    0x1d614: 'M',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL M}
    0x1d648: 'M',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL M}
    0x1d67c: 'M',  # \N{MATHEMATICAL MONOSPACE CAPITAL M}
    0x39c: 'M',  # \N{GREEK CAPITAL LETTER MU}
    0x1d6b3: 'M',  # \N{MATHEMATICAL BOLD CAPITAL MU}
    0x1d6ed: 'M',  # \N{MATHEMATICAL ITALIC CAPITAL MU}
    0x1d727: 'M',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL MU}
    0x1d761: 'M',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL MU}
    0x1d79b: 'M',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL MU}
    0x3fa: 'M',  # \N{GREEK CAPITAL LETTER SAN}
    0x2c98: 'M',  # \N{COPTIC CAPITAL LETTER MI}
    0x41c: 'M',  # \N{CYRILLIC CAPITAL LETTER EM}
    0x13b7: 'M',  # \N{CHEROKEE LETTER LU}
    0x15f0: 'M',  # \N{CANADIAN SYLLABICS CARRIER GO}
    0x16d6: 'M',  # \N{RUNIC LETTER EHWAZ EH E}
    0xa4df: 'M',  # \N{LISU LETTER MA}
    0x102b0: 'M',  # \N{CARIAN LETTER S}
    0x10311: 'M',  # \N{OLD ITALIC LETTER SHE}
    0x1f76b: 'MB',  # \N{ALCHEMICAL SYMBOL FOR BATH OF MARY}
    0x1d427: 'n',  # \N{MATHEMATICAL BOLD SMALL N}
    0x1d45b: 'n',  # \N{MATHEMATICAL ITALIC SMALL N}
    0x1d48f: 'n',  # \N{MATHEMATICAL BOLD ITALIC SMALL N}
    0x1d4c3: 'n',  # \N{MATHEMATICAL SCRIPT SMALL N}
    0x1d4f7: 'n',  # \N{MATHEMATICAL BOLD SCRIPT SMALL N}
    0x1d52b: 'n',  # \N{MATHEMATICAL FRAKTUR SMALL N}
    0x1d55f: 'n',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL N}
    0x1d593: 'n',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL N}
    0x1d5c7: 'n',  # \N{MATHEMATICAL SANS-SERIF SMALL N}
    0x1d5fb: 'n',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL N}
    0x1d62f: 'n',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL N}
    0x1d663: 'n',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL N}
    0x1d697: 'n',  # \N{MATHEMATICAL MONOSPACE SMALL N}
    0x578: 'n',  # \N{ARMENIAN SMALL LETTER VO}
    0x57c: 'n',  # \N{ARMENIAN SMALL LETTER RA}
    0xff2e: 'N',  # \N{FULLWIDTH LATIN CAPITAL LETTER N}
    0x2115: 'N',  # \N{DOUBLE-STRUCK CAPITAL N}
    0x1d40d: 'N',  # \N{MATHEMATICAL BOLD CAPITAL N}
    0x1d441: 'N',  # \N{MATHEMATICAL ITALIC CAPITAL N}
    0x1d475: 'N',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL N}
    0x1d4a9: 'N',  # \N{MATHEMATICAL SCRIPT CAPITAL N}
    0x1d4dd: 'N',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL N}
    0x1d511: 'N',  # \N{MATHEMATICAL FRAKTUR CAPITAL N}
    0x1d579: 'N',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL N}
    0x1d5ad: 'N',  # \N{MATHEMATICAL SANS-SERIF CAPITAL N}
    0x1d5e1: 'N',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL N}
    0x1d615: 'N',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL N}
    0x1d649: 'N',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL N}
    0x1d67d: 'N',  # \N{MATHEMATICAL MONOSPACE CAPITAL N}
    0x39d: 'N',  # \N{GREEK CAPITAL LETTER NU}
    0x1d6b4: 'N',  # \N{MATHEMATICAL BOLD CAPITAL NU}
    0x1d6ee: 'N',  # \N{MATHEMATICAL ITALIC CAPITAL NU}
    0x1d728: 'N',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL NU}
    0x1d762: 'N',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL NU}
    0x1d79c: 'N',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL NU}
    0x2c9a: 'N',  # \N{COPTIC CAPITAL LETTER NI}
    0xa4e0: 'N',  # \N{LISU LETTER NA}
    0x10513: 'N',  # \N{ELBASAN LETTER NE}
    0x1cc: 'nj',  # \N{LATIN SMALL LETTER NJ}
    0x1cb: 'Nj',  # \N{LATIN CAPITAL LETTER N WITH SMALL LETTER J}
    0x1ca: 'NJ',  # \N{LATIN CAPITAL LETTER NJ}
    0x2116: 'No',  # \N{NUMERO SIGN}
    0xc02: 'o',  # \N{TELUGU SIGN ANUSVARA}
    0xc82: 'o',  # \N{KANNADA SIGN ANUSVARA}
    0xd02: 'o',  # \N{MALAYALAM SIGN ANUSVARA}
    0xd82: 'o',  # \N{SINHALA SIGN ANUSVARAYA}
    0x966: 'o',  # \N{DEVANAGARI DIGIT ZERO}
    0xa66: 'o',  # \N{GURMUKHI DIGIT ZERO}
    0xae6: 'o',  # \N{GUJARATI DIGIT ZERO}
    0xbe6: 'o',  # \N{TAMIL DIGIT ZERO}
    0xc66: 'o',  # \N{TELUGU DIGIT ZERO}
    0xce6: 'o',  # \N{KANNADA DIGIT ZERO}
    0xd66: 'o',  # \N{MALAYALAM DIGIT ZERO}
    0xe50: 'o',  # \N{THAI DIGIT ZERO}
    0xed0: 'o',  # \N{LAO DIGIT ZERO}
    0x1040: 'o',  # \N{MYANMAR DIGIT ZERO}
    0x665: 'o',  # \N{ARABIC-INDIC DIGIT FIVE}
    0x6f5: 'o',  # \N{EXTENDED ARABIC-INDIC DIGIT FIVE}
    0xff4f: 'o',  # \N{FULLWIDTH LATIN SMALL LETTER O}
    0x2134: 'o',  # \N{SCRIPT SMALL O}
    0x1d428: 'o',  # \N{MATHEMATICAL BOLD SMALL O}
    0x1d45c: 'o',  # \N{MATHEMATICAL ITALIC SMALL O}
    0x1d490: 'o',  # \N{MATHEMATICAL BOLD ITALIC SMALL O}
    0x1d4f8: 'o',  # \N{MATHEMATICAL BOLD SCRIPT SMALL O}
    0x1d52c: 'o',  # \N{MATHEMATICAL FRAKTUR SMALL O}
    0x1d560: 'o',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL O}
    0x1d594: 'o',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL O}
    0x1d5c8: 'o',  # \N{MATHEMATICAL SANS-SERIF SMALL O}
    0x1d5fc: 'o',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL O}
    0x1d630: 'o',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL O}
    0x1d664: 'o',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL O}
    0x1d698: 'o',  # \N{MATHEMATICAL MONOSPACE SMALL O}
    0x1d0f: 'o',  # \N{LATIN LETTER SMALL CAPITAL O}
    0x1d11: 'o',  # \N{LATIN SMALL LETTER SIDEWAYS O}
    0xab3d: 'o',  # \N{LATIN SMALL LETTER BLACKLETTER O}
    0x3bf: 'o',  # \N{GREEK SMALL LETTER OMICRON}
    0x1d6d0: 'o',  # \N{MATHEMATICAL BOLD SMALL OMICRON}
    0x1d70a: 'o',  # \N{MATHEMATICAL ITALIC SMALL OMICRON}
    0x1d744: 'o',  # \N{MATHEMATICAL BOLD ITALIC SMALL OMICRON}
    0x1d77e: 'o',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL OMICRON}
    0x1d7b8: 'o',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL OMICRON}
    0x3c3: 'o',  # \N{GREEK SMALL LETTER SIGMA}
    0x1d6d4: 'o',  # \N{MATHEMATICAL BOLD SMALL SIGMA}
    0x1d70e: 'o',  # \N{MATHEMATICAL ITALIC SMALL SIGMA}
    0x1d748: 'o',  # \N{MATHEMATICAL BOLD ITALIC SMALL SIGMA}
    0x1d782: 'o',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL SIGMA}
    0x1d7bc: 'o',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL SIGMA}
    0x2c9f: 'o',  # \N{COPTIC SMALL LETTER O}
    0x43e: 'o',  # \N{CYRILLIC SMALL LETTER O}
    0x10ff: 'o',  # \N{GEORGIAN LETTER LABIAL SIGN}
    0x585: 'o',  # \N{ARMENIAN SMALL LETTER OH}
    0x5e1: 'o',  # \N{HEBREW LETTER SAMEKH}
    0x647: 'o',  # \N{ARABIC LETTER HEH}
    0x1ee24: 'o',  # \N{ARABIC MATHEMATICAL INITIAL HEH}
    0x1ee64: 'o',  # \N{ARABIC MATHEMATICAL STRETCHED HEH}
    0x1ee84: 'o',  # \N{ARABIC MATHEMATICAL LOOPED HEH}
    0xfeeb: 'o',  # \N{ARABIC LETTER HEH INITIAL FORM}
    0xfeec: 'o',  # \N{ARABIC LETTER HEH MEDIAL FORM}
    0xfeea: 'o',  # \N{ARABIC LETTER HEH FINAL FORM}
    0xfee9: 'o',  # \N{ARABIC LETTER HEH ISOLATED FORM}
    0x6be: 'o',  # \N{ARABIC LETTER HEH DOACHASHMEE}
    0xfbac: 'o',  # \N{ARABIC LETTER HEH DOACHASHMEE INITIAL FORM}
    0xfbad: 'o',  # \N{ARABIC LETTER HEH DOACHASHMEE MEDIAL FORM}
    0xfbab: 'o',  # \N{ARABIC LETTER HEH DOACHASHMEE FINAL FORM}
    0xfbaa: 'o',  # \N{ARABIC LETTER HEH DOACHASHMEE ISOLATED FORM}
    0x6c1: 'o',  # \N{ARABIC LETTER HEH GOAL}
    0xfba8: 'o',  # \N{ARABIC LETTER HEH GOAL INITIAL FORM}
    0xfba9: 'o',  # \N{ARABIC LETTER HEH GOAL MEDIAL FORM}
    0xfba7: 'o',  # \N{ARABIC LETTER HEH GOAL FINAL FORM}
    0xfba6: 'o',  # \N{ARABIC LETTER HEH GOAL ISOLATED FORM}
    0x6d5: 'o',  # \N{ARABIC LETTER AE}
    0xd20: 'o',  # \N{MALAYALAM LETTER TTHA}
    0x101d: 'o',  # \N{MYANMAR LETTER WA}
    0x104ea: 'o',  # \N{OSAGE SMALL LETTER O}
    0x118c8: 'o',  # \N{WARANG CITI SMALL LETTER E}
    0x118d7: 'o',  # \N{WARANG CITI SMALL LETTER BU}
    0x1042c: 'o',  # \N{DESERET SMALL LETTER LONG O}
# ignoring: 0 -> O
    0x7c0: 'O',  # \N{NKO DIGIT ZERO}
    0x9e6: 'O',  # \N{BENGALI DIGIT ZERO}
    0xb66: 'O',  # \N{ORIYA DIGIT ZERO}
    0x3007: 'O',  # \N{IDEOGRAPHIC NUMBER ZERO}
    0x114d0: 'O',  # \N{TIRHUTA DIGIT ZERO}
    0x118e0: 'O',  # \N{WARANG CITI DIGIT ZERO}
    0x1d7ce: 'O',  # \N{MATHEMATICAL BOLD DIGIT ZERO}
    0x1d7d8: 'O',  # \N{MATHEMATICAL DOUBLE-STRUCK DIGIT ZERO}
    0x1d7e2: 'O',  # \N{MATHEMATICAL SANS-SERIF DIGIT ZERO}
    0x1d7ec: 'O',  # \N{MATHEMATICAL SANS-SERIF BOLD DIGIT ZERO}
    0x1d7f6: 'O',  # \N{MATHEMATICAL MONOSPACE DIGIT ZERO}
    0x1fbf0: 'O',  # \N{SEGMENTED DIGIT ZERO}
    0xff2f: 'O',  # \N{FULLWIDTH LATIN CAPITAL LETTER O}
    0x1d40e: 'O',  # \N{MATHEMATICAL BOLD CAPITAL O}
    0x1d442: 'O',  # \N{MATHEMATICAL ITALIC CAPITAL O}
    0x1d476: 'O',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL O}
    0x1d4aa: 'O',  # \N{MATHEMATICAL SCRIPT CAPITAL O}
    0x1d4de: 'O',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL O}
    0x1d512: 'O',  # \N{MATHEMATICAL FRAKTUR CAPITAL O}
    0x1d546: 'O',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL O}
    0x1d57a: 'O',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL O}
    0x1d5ae: 'O',  # \N{MATHEMATICAL SANS-SERIF CAPITAL O}
    0x1d5e2: 'O',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL O}
    0x1d616: 'O',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL O}
    0x1d64a: 'O',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL O}
    0x1d67e: 'O',  # \N{MATHEMATICAL MONOSPACE CAPITAL O}
    0x39f: 'O',  # \N{GREEK CAPITAL LETTER OMICRON}
    0x1d6b6: 'O',  # \N{MATHEMATICAL BOLD CAPITAL OMICRON}
    0x1d6f0: 'O',  # \N{MATHEMATICAL ITALIC CAPITAL OMICRON}
    0x1d72a: 'O',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL OMICRON}
    0x1d764: 'O',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL OMICRON}
    0x1d79e: 'O',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL OMICRON}
    0x2c9e: 'O',  # \N{COPTIC CAPITAL LETTER O}
    0x41e: 'O',  # \N{CYRILLIC CAPITAL LETTER O}
    0x555: 'O',  # \N{ARMENIAN CAPITAL LETTER OH}
    0x2d54: 'O',  # \N{TIFINAGH LETTER YAR}
    0x12d0: 'O',  # \N{ETHIOPIC SYLLABLE PHARYNGEAL A}
    0xb20: 'O',  # \N{ORIYA LETTER TTHA}
    0x104c2: 'O',  # \N{OSAGE CAPITAL LETTER O}
    0xa4f3: 'O',  # \N{LISU LETTER O}
    0x118b5: 'O',  # \N{WARANG CITI CAPITAL LETTER AT}
    0x10292: 'O',  # \N{LYCIAN LETTER U}
    0x102ab: 'O',  # \N{CARIAN LETTER O}
    0x10404: 'O',  # \N{DESERET CAPITAL LETTER LONG O}
    0x10516: 'O',  # \N{ELBASAN LETTER O}
    0x1f101: 'O,',  # \N{DIGIT ZERO COMMA}
    0x1f100: 'O.',  # \N{DIGIT ZERO FULL STOP}
    0x1a1: "o'",  # \N{LATIN SMALL LETTER O WITH HORN}
    0x1a0: "O'",  # \N{LATIN CAPITAL LETTER O WITH HORN}
    0x13a4: "O'",  # \N{CHEROKEE LETTER U}
# ignoring: % -> \N{MASCULINE ORDINAL INDICATOR}/\N{SUBSCRIPT ZERO}
    0x153: 'oe',  # \N{LATIN SMALL LIGATURE OE}
    0x152: 'OE',  # \N{LATIN CAPITAL LIGATURE OE}
    0x221e: 'oo',  # \N{INFINITY}
    0xa74f: 'oo',  # \N{LATIN SMALL LETTER OO}
    0xa699: 'oo',  # \N{CYRILLIC SMALL LETTER DOUBLE O}
    0xa74e: 'OO',  # \N{LATIN CAPITAL LETTER OO}
    0xa698: 'OO',  # \N{CYRILLIC CAPITAL LETTER DOUBLE O}
    0x2374: 'p',  # \N{APL FUNCTIONAL SYMBOL RHO}
    0xff50: 'p',  # \N{FULLWIDTH LATIN SMALL LETTER P}
    0x1d429: 'p',  # \N{MATHEMATICAL BOLD SMALL P}
    0x1d45d: 'p',  # \N{MATHEMATICAL ITALIC SMALL P}
    0x1d491: 'p',  # \N{MATHEMATICAL BOLD ITALIC SMALL P}
    0x1d4c5: 'p',  # \N{MATHEMATICAL SCRIPT SMALL P}
    0x1d4f9: 'p',  # \N{MATHEMATICAL BOLD SCRIPT SMALL P}
    0x1d52d: 'p',  # \N{MATHEMATICAL FRAKTUR SMALL P}
    0x1d561: 'p',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL P}
    0x1d595: 'p',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL P}
    0x1d5c9: 'p',  # \N{MATHEMATICAL SANS-SERIF SMALL P}
    0x1d5fd: 'p',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL P}
    0x1d631: 'p',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL P}
    0x1d665: 'p',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL P}
    0x1d699: 'p',  # \N{MATHEMATICAL MONOSPACE SMALL P}
    0x3c1: 'p',  # \N{GREEK SMALL LETTER RHO}
    0x3f1: 'p',  # \N{GREEK RHO SYMBOL}
    0x1d6d2: 'p',  # \N{MATHEMATICAL BOLD SMALL RHO}
    0x1d6e0: 'p',  # \N{MATHEMATICAL BOLD RHO SYMBOL}
    0x1d70c: 'p',  # \N{MATHEMATICAL ITALIC SMALL RHO}
    0x1d71a: 'p',  # \N{MATHEMATICAL ITALIC RHO SYMBOL}
    0x1d746: 'p',  # \N{MATHEMATICAL BOLD ITALIC SMALL RHO}
    0x1d754: 'p',  # \N{MATHEMATICAL BOLD ITALIC RHO SYMBOL}
    0x1d780: 'p',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL RHO}
    0x1d78e: 'p',  # \N{MATHEMATICAL SANS-SERIF BOLD RHO SYMBOL}
    0x1d7ba: 'p',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL RHO}
    0x1d7c8: 'p',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC RHO SYMBOL}
    0x2ca3: 'p',  # \N{COPTIC SMALL LETTER RO}
    0x440: 'p',  # \N{CYRILLIC SMALL LETTER ER}
    0xff30: 'P',  # \N{FULLWIDTH LATIN CAPITAL LETTER P}
    0x2119: 'P',  # \N{DOUBLE-STRUCK CAPITAL P}
    0x1d40f: 'P',  # \N{MATHEMATICAL BOLD CAPITAL P}
    0x1d443: 'P',  # \N{MATHEMATICAL ITALIC CAPITAL P}
    0x1d477: 'P',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL P}
    0x1d4ab: 'P',  # \N{MATHEMATICAL SCRIPT CAPITAL P}
    0x1d4df: 'P',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL P}
    0x1d513: 'P',  # \N{MATHEMATICAL FRAKTUR CAPITAL P}
    0x1d57b: 'P',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL P}
    0x1d5af: 'P',  # \N{MATHEMATICAL SANS-SERIF CAPITAL P}
    0x1d5e3: 'P',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL P}
    0x1d617: 'P',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL P}
    0x1d64b: 'P',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL P}
    0x1d67f: 'P',  # \N{MATHEMATICAL MONOSPACE CAPITAL P}
    0x3a1: 'P',  # \N{GREEK CAPITAL LETTER RHO}
    0x1d6b8: 'P',  # \N{MATHEMATICAL BOLD CAPITAL RHO}
    0x1d6f2: 'P',  # \N{MATHEMATICAL ITALIC CAPITAL RHO}
    0x1d72c: 'P',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL RHO}
    0x1d766: 'P',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL RHO}
    0x1d7a0: 'P',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL RHO}
    0x2ca2: 'P',  # \N{COPTIC CAPITAL LETTER RO}
    0x420: 'P',  # \N{CYRILLIC CAPITAL LETTER ER}
    0x13e2: 'P',  # \N{CHEROKEE LETTER TLV}
    0x146d: 'P',  # \N{CANADIAN SYLLABICS KI}
    0xa4d1: 'P',  # \N{LISU LETTER PA}
    0x10295: 'P',  # \N{LYCIAN LETTER R}
    0x1486: "P'",  # \N{CANADIAN SYLLABICS SOUTH-SLAVEY KIH}
    0x1d42a: 'q',  # \N{MATHEMATICAL BOLD SMALL Q}
    0x1d45e: 'q',  # \N{MATHEMATICAL ITALIC SMALL Q}
    0x1d492: 'q',  # \N{MATHEMATICAL BOLD ITALIC SMALL Q}
    0x1d4c6: 'q',  # \N{MATHEMATICAL SCRIPT SMALL Q}
    0x1d4fa: 'q',  # \N{MATHEMATICAL BOLD SCRIPT SMALL Q}
    0x1d52e: 'q',  # \N{MATHEMATICAL FRAKTUR SMALL Q}
    0x1d562: 'q',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL Q}
    0x1d596: 'q',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL Q}
    0x1d5ca: 'q',  # \N{MATHEMATICAL SANS-SERIF SMALL Q}
    0x1d5fe: 'q',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL Q}
    0x1d632: 'q',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL Q}
    0x1d666: 'q',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Q}
    0x1d69a: 'q',  # \N{MATHEMATICAL MONOSPACE SMALL Q}
    0x51b: 'q',  # \N{CYRILLIC SMALL LETTER QA}
    0x563: 'q',  # \N{ARMENIAN SMALL LETTER GIM}
    0x566: 'q',  # \N{ARMENIAN SMALL LETTER ZA}
    0x211a: 'Q',  # \N{DOUBLE-STRUCK CAPITAL Q}
    0x1d410: 'Q',  # \N{MATHEMATICAL BOLD CAPITAL Q}
    0x1d444: 'Q',  # \N{MATHEMATICAL ITALIC CAPITAL Q}
    0x1d478: 'Q',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL Q}
    0x1d4ac: 'Q',  # \N{MATHEMATICAL SCRIPT CAPITAL Q}
    0x1d4e0: 'Q',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL Q}
    0x1d514: 'Q',  # \N{MATHEMATICAL FRAKTUR CAPITAL Q}
    0x1d57c: 'Q',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL Q}
    0x1d5b0: 'Q',  # \N{MATHEMATICAL SANS-SERIF CAPITAL Q}
    0x1d5e4: 'Q',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL Q}
    0x1d618: 'Q',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL Q}
    0x1d64c: 'Q',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Q}
    0x1d680: 'Q',  # \N{MATHEMATICAL MONOSPACE CAPITAL Q}
    0x2d55: 'Q',  # \N{TIFINAGH LETTER YARR}
    0x1f700: 'QE',  # \N{ALCHEMICAL SYMBOL FOR QUINTESSENCE}
    0x1d42b: 'r',  # \N{MATHEMATICAL BOLD SMALL R}
    0x1d45f: 'r',  # \N{MATHEMATICAL ITALIC SMALL R}
    0x1d493: 'r',  # \N{MATHEMATICAL BOLD ITALIC SMALL R}
    0x1d4c7: 'r',  # \N{MATHEMATICAL SCRIPT SMALL R}
    0x1d4fb: 'r',  # \N{MATHEMATICAL BOLD SCRIPT SMALL R}
    0x1d52f: 'r',  # \N{MATHEMATICAL FRAKTUR SMALL R}
    0x1d563: 'r',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL R}
    0x1d597: 'r',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL R}
    0x1d5cb: 'r',  # \N{MATHEMATICAL SANS-SERIF SMALL R}
    0x1d5ff: 'r',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL R}
    0x1d633: 'r',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL R}
    0x1d667: 'r',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL R}
    0x1d69b: 'r',  # \N{MATHEMATICAL MONOSPACE SMALL R}
    0xab47: 'r',  # \N{LATIN SMALL LETTER R WITHOUT HANDLE}
    0xab48: 'r',  # \N{LATIN SMALL LETTER DOUBLE R}
    0x1d26: 'r',  # \N{GREEK LETTER SMALL CAPITAL GAMMA}
    0x2c85: 'r',  # \N{COPTIC SMALL LETTER GAMMA}
    0x433: 'r',  # \N{CYRILLIC SMALL LETTER GHE}
    0xab81: 'r',  # \N{CHEROKEE SMALL LETTER HU}
    0x1d216: 'R',  # \N{GREEK VOCAL NOTATION SYMBOL-23}
    0x211b: 'R',  # \N{SCRIPT CAPITAL R}
    0x211c: 'R',  # \N{BLACK-LETTER CAPITAL R}
    0x211d: 'R',  # \N{DOUBLE-STRUCK CAPITAL R}
    0x1d411: 'R',  # \N{MATHEMATICAL BOLD CAPITAL R}
    0x1d445: 'R',  # \N{MATHEMATICAL ITALIC CAPITAL R}
    0x1d479: 'R',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL R}
    0x1d4e1: 'R',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL R}
    0x1d57d: 'R',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL R}
    0x1d5b1: 'R',  # \N{MATHEMATICAL SANS-SERIF CAPITAL R}
    0x1d5e5: 'R',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL R}
    0x1d619: 'R',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL R}
    0x1d64d: 'R',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL R}
    0x1d681: 'R',  # \N{MATHEMATICAL MONOSPACE CAPITAL R}
    0x1a6: 'R',  # \N{LATIN LETTER YR}
    0x13a1: 'R',  # \N{CHEROKEE LETTER E}
    0x13d2: 'R',  # \N{CHEROKEE LETTER SV}
    0x104b4: 'R',  # \N{OSAGE CAPITAL LETTER BRA}
    0x1587: 'R',  # \N{CANADIAN SYLLABICS TLHI}
    0xa4e3: 'R',  # \N{LISU LETTER ZHA}
    0x16f35: 'R',  # \N{MIAO LETTER ZHA}
    0x491: "r'",  # \N{CYRILLIC SMALL LETTER GHE WITH UPTURN}
    0x118e3: 'rn',  # \N{WARANG CITI DIGIT THREE}
# ignoring: m -> rn
    0x217f: 'rn',  # \N{SMALL ROMAN NUMERAL ONE THOUSAND}
    0x1d426: 'rn',  # \N{MATHEMATICAL BOLD SMALL M}
    0x1d45a: 'rn',  # \N{MATHEMATICAL ITALIC SMALL M}
    0x1d48e: 'rn',  # \N{MATHEMATICAL BOLD ITALIC SMALL M}
    0x1d4c2: 'rn',  # \N{MATHEMATICAL SCRIPT SMALL M}
    0x1d4f6: 'rn',  # \N{MATHEMATICAL BOLD SCRIPT SMALL M}
    0x1d52a: 'rn',  # \N{MATHEMATICAL FRAKTUR SMALL M}
    0x1d55e: 'rn',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL M}
    0x1d592: 'rn',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL M}
    0x1d5c6: 'rn',  # \N{MATHEMATICAL SANS-SERIF SMALL M}
    0x1d5fa: 'rn',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL M}
    0x1d62e: 'rn',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL M}
    0x1d662: 'rn',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL M}
    0x1d696: 'rn',  # \N{MATHEMATICAL MONOSPACE SMALL M}
    0x11700: 'rn',  # \N{AHOM LETTER KA}
    0x20a8: 'Rs',  # \N{RUPEE SIGN}
    0xff53: 's',  # \N{FULLWIDTH LATIN SMALL LETTER S}
    0x1d42c: 's',  # \N{MATHEMATICAL BOLD SMALL S}
    0x1d460: 's',  # \N{MATHEMATICAL ITALIC SMALL S}
    0x1d494: 's',  # \N{MATHEMATICAL BOLD ITALIC SMALL S}
    0x1d4c8: 's',  # \N{MATHEMATICAL SCRIPT SMALL S}
    0x1d4fc: 's',  # \N{MATHEMATICAL BOLD SCRIPT SMALL S}
    0x1d530: 's',  # \N{MATHEMATICAL FRAKTUR SMALL S}
    0x1d564: 's',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL S}
    0x1d598: 's',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL S}
    0x1d5cc: 's',  # \N{MATHEMATICAL SANS-SERIF SMALL S}
    0x1d600: 's',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL S}
    0x1d634: 's',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL S}
    0x1d668: 's',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL S}
    0x1d69c: 's',  # \N{MATHEMATICAL MONOSPACE SMALL S}
    0xa731: 's',  # \N{LATIN LETTER SMALL CAPITAL S}
    0x1bd: 's',  # \N{LATIN SMALL LETTER TONE FIVE}
    0x455: 's',  # \N{CYRILLIC SMALL LETTER DZE}
    0xabaa: 's',  # \N{CHEROKEE SMALL LETTER DU}
    0x118c1: 's',  # \N{WARANG CITI SMALL LETTER A}
    0x10448: 's',  # \N{DESERET SMALL LETTER ZHEE}
    0xff33: 'S',  # \N{FULLWIDTH LATIN CAPITAL LETTER S}
    0x1d412: 'S',  # \N{MATHEMATICAL BOLD CAPITAL S}
    0x1d446: 'S',  # \N{MATHEMATICAL ITALIC CAPITAL S}
    0x1d47a: 'S',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL S}
    0x1d4ae: 'S',  # \N{MATHEMATICAL SCRIPT CAPITAL S}
    0x1d4e2: 'S',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL S}
    0x1d516: 'S',  # \N{MATHEMATICAL FRAKTUR CAPITAL S}
    0x1d54a: 'S',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL S}
    0x1d57e: 'S',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL S}
    0x1d5b2: 'S',  # \N{MATHEMATICAL SANS-SERIF CAPITAL S}
    0x1d5e6: 'S',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL S}
    0x1d61a: 'S',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL S}
    0x1d64e: 'S',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL S}
    0x1d682: 'S',  # \N{MATHEMATICAL MONOSPACE CAPITAL S}
    0x405: 'S',  # \N{CYRILLIC CAPITAL LETTER DZE}
    0x54f: 'S',  # \N{ARMENIAN CAPITAL LETTER TIWN}
    0x13d5: 'S',  # \N{CHEROKEE LETTER DE}
    0x13da: 'S',  # \N{CHEROKEE LETTER DU}
    0xa4e2: 'S',  # \N{LISU LETTER SA}
    0x16f3a: 'S',  # \N{MIAO LETTER SA}
    0x10296: 'S',  # \N{LYCIAN LETTER S}
    0x10420: 'S',  # \N{DESERET CAPITAL LETTER ZHEE}
    0x1f75c: 'sss',  # \N{ALCHEMICAL SYMBOL FOR STRATUM SUPER STRATUM}
    0xfb06: 'st',  # \N{LATIN SMALL LIGATURE ST}
    0x1d42d: 't',  # \N{MATHEMATICAL BOLD SMALL T}
    0x1d461: 't',  # \N{MATHEMATICAL ITALIC SMALL T}
    0x1d495: 't',  # \N{MATHEMATICAL BOLD ITALIC SMALL T}
    0x1d4c9: 't',  # \N{MATHEMATICAL SCRIPT SMALL T}
    0x1d4fd: 't',  # \N{MATHEMATICAL BOLD SCRIPT SMALL T}
    0x1d531: 't',  # \N{MATHEMATICAL FRAKTUR SMALL T}
    0x1d565: 't',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL T}
    0x1d599: 't',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL T}
    0x1d5cd: 't',  # \N{MATHEMATICAL SANS-SERIF SMALL T}
    0x1d601: 't',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL T}
    0x1d635: 't',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL T}
    0x1d669: 't',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL T}
    0x1d69d: 't',  # \N{MATHEMATICAL MONOSPACE SMALL T}
    0x22a4: 'T',  # \N{DOWN TACK}
    0x27d9: 'T',  # \N{LARGE DOWN TACK}
    0x1f768: 'T',  # \N{ALCHEMICAL SYMBOL FOR CRUCIBLE-4}
    0xff34: 'T',  # \N{FULLWIDTH LATIN CAPITAL LETTER T}
    0x1d413: 'T',  # \N{MATHEMATICAL BOLD CAPITAL T}
    0x1d447: 'T',  # \N{MATHEMATICAL ITALIC CAPITAL T}
    0x1d47b: 'T',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL T}
    0x1d4af: 'T',  # \N{MATHEMATICAL SCRIPT CAPITAL T}
    0x1d4e3: 'T',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL T}
    0x1d517: 'T',  # \N{MATHEMATICAL FRAKTUR CAPITAL T}
    0x1d54b: 'T',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL T}
    0x1d57f: 'T',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL T}
    0x1d5b3: 'T',  # \N{MATHEMATICAL SANS-SERIF CAPITAL T}
    0x1d5e7: 'T',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL T}
    0x1d61b: 'T',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL T}
    0x1d64f: 'T',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL T}
    0x1d683: 'T',  # \N{MATHEMATICAL MONOSPACE CAPITAL T}
    0x3a4: 'T',  # \N{GREEK CAPITAL LETTER TAU}
    0x1d6bb: 'T',  # \N{MATHEMATICAL BOLD CAPITAL TAU}
    0x1d6f5: 'T',  # \N{MATHEMATICAL ITALIC CAPITAL TAU}
    0x1d72f: 'T',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL TAU}
    0x1d769: 'T',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL TAU}
    0x1d7a3: 'T',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL TAU}
    0x2ca6: 'T',  # \N{COPTIC CAPITAL LETTER TAU}
    0x422: 'T',  # \N{CYRILLIC CAPITAL LETTER TE}
    0x13a2: 'T',  # \N{CHEROKEE LETTER I}
    0xa4d4: 'T',  # \N{LISU LETTER TA}
    0x16f0a: 'T',  # \N{MIAO LETTER TA}
    0x118bc: 'T',  # \N{WARANG CITI CAPITAL LETTER HAR}
    0x10297: 'T',  # \N{LYCIAN LETTER T}
    0x102b1: 'T',  # \N{CARIAN LETTER C-18}
    0x10315: 'T',  # \N{OLD ITALIC LETTER TE}
    0xa728: 'T3',  # \N{LATIN CAPITAL LETTER TZ}
    0x2121: 'TEL',  # \N{TELEPHONE SIGN}
    0xa777: 'tf',  # \N{LATIN SMALL LETTER TUM}
    0x2a6: 'ts',  # \N{LATIN SMALL LETTER TS DIGRAPH}
    0x1d42e: 'u',  # \N{MATHEMATICAL BOLD SMALL U}
    0x1d462: 'u',  # \N{MATHEMATICAL ITALIC SMALL U}
    0x1d496: 'u',  # \N{MATHEMATICAL BOLD ITALIC SMALL U}
    0x1d4ca: 'u',  # \N{MATHEMATICAL SCRIPT SMALL U}
    0x1d4fe: 'u',  # \N{MATHEMATICAL BOLD SCRIPT SMALL U}
    0x1d532: 'u',  # \N{MATHEMATICAL FRAKTUR SMALL U}
    0x1d566: 'u',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL U}
    0x1d59a: 'u',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL U}
    0x1d5ce: 'u',  # \N{MATHEMATICAL SANS-SERIF SMALL U}
    0x1d602: 'u',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL U}
    0x1d636: 'u',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL U}
    0x1d66a: 'u',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL U}
    0x1d69e: 'u',  # \N{MATHEMATICAL MONOSPACE SMALL U}
    0xa79f: 'u',  # \N{LATIN SMALL LETTER VOLAPUK UE}
    0x1d1c: 'u',  # \N{LATIN LETTER SMALL CAPITAL U}
    0xab4e: 'u',  # \N{LATIN SMALL LETTER U WITH SHORT RIGHT LEG}
    0xab52: 'u',  # \N{LATIN SMALL LETTER U WITH LEFT HOOK}
    0x28b: 'u',  # \N{LATIN SMALL LETTER V WITH HOOK}
    0x3c5: 'u',  # \N{GREEK SMALL LETTER UPSILON}
    0x1d6d6: 'u',  # \N{MATHEMATICAL BOLD SMALL UPSILON}
    0x1d710: 'u',  # \N{MATHEMATICAL ITALIC SMALL UPSILON}
    0x1d74a: 'u',  # \N{MATHEMATICAL BOLD ITALIC SMALL UPSILON}
    0x1d784: 'u',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL UPSILON}
    0x1d7be: 'u',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL UPSILON}
    0x57d: 'u',  # \N{ARMENIAN SMALL LETTER SEH}
    0x104f6: 'u',  # \N{OSAGE SMALL LETTER U}
    0x118d8: 'u',  # \N{WARANG CITI SMALL LETTER PU}
    0x222a: 'U',  # \N{UNION}
    0x22c3: 'U',  # \N{N-ARY UNION}
    0x1d414: 'U',  # \N{MATHEMATICAL BOLD CAPITAL U}
    0x1d448: 'U',  # \N{MATHEMATICAL ITALIC CAPITAL U}
    0x1d47c: 'U',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL U}
    0x1d4b0: 'U',  # \N{MATHEMATICAL SCRIPT CAPITAL U}
    0x1d4e4: 'U',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL U}
    0x1d518: 'U',  # \N{MATHEMATICAL FRAKTUR CAPITAL U}
    0x1d54c: 'U',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL U}
    0x1d580: 'U',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL U}
    0x1d5b4: 'U',  # \N{MATHEMATICAL SANS-SERIF CAPITAL U}
    0x1d5e8: 'U',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL U}
    0x1d61c: 'U',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL U}
    0x1d650: 'U',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL U}
    0x1d684: 'U',  # \N{MATHEMATICAL MONOSPACE CAPITAL U}
    0x54d: 'U',  # \N{ARMENIAN CAPITAL LETTER SEH}
    0x1200: 'U',  # \N{ETHIOPIC SYLLABLE HA}
    0x104ce: 'U',  # \N{OSAGE CAPITAL LETTER U}
    0x144c: 'U',  # \N{CANADIAN SYLLABICS TE}
    0xa4f4: 'U',  # \N{LISU LETTER U}
    0x16f42: 'U',  # \N{MIAO LETTER WA}
    0x118b8: 'U',  # \N{WARANG CITI CAPITAL LETTER PU}
    0x1467: "U'",  # \N{CANADIAN SYLLABICS TTE}
    0x1d6b: 'ue',  # \N{LATIN SMALL LETTER UE}
    0xab63: 'uo',  # \N{LATIN SMALL LETTER UO}
    0x2228: 'v',  # \N{LOGICAL OR}
    0x22c1: 'v',  # \N{N-ARY LOGICAL OR}
    0xff56: 'v',  # \N{FULLWIDTH LATIN SMALL LETTER V}
    0x2174: 'v',  # \N{SMALL ROMAN NUMERAL FIVE}
    0x1d42f: 'v',  # \N{MATHEMATICAL BOLD SMALL V}
    0x1d463: 'v',  # \N{MATHEMATICAL ITALIC SMALL V}
    0x1d497: 'v',  # \N{MATHEMATICAL BOLD ITALIC SMALL V}
    0x1d4cb: 'v',  # \N{MATHEMATICAL SCRIPT SMALL V}
    0x1d4ff: 'v',  # \N{MATHEMATICAL BOLD SCRIPT SMALL V}
    0x1d533: 'v',  # \N{MATHEMATICAL FRAKTUR SMALL V}
    0x1d567: 'v',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL V}
    0x1d59b: 'v',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL V}
    0x1d5cf: 'v',  # \N{MATHEMATICAL SANS-SERIF SMALL V}
    0x1d603: 'v',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL V}
    0x1d637: 'v',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL V}
    0x1d66b: 'v',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL V}
    0x1d69f: 'v',  # \N{MATHEMATICAL MONOSPACE SMALL V}
    0x1d20: 'v',  # \N{LATIN LETTER SMALL CAPITAL V}
    0x3bd: 'v',  # \N{GREEK SMALL LETTER NU}
    0x1d6ce: 'v',  # \N{MATHEMATICAL BOLD SMALL NU}
    0x1d708: 'v',  # \N{MATHEMATICAL ITALIC SMALL NU}
    0x1d742: 'v',  # \N{MATHEMATICAL BOLD ITALIC SMALL NU}
    0x1d77c: 'v',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL NU}
    0x1d7b6: 'v',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL NU}
    0x475: 'v',  # \N{CYRILLIC SMALL LETTER IZHITSA}
    0x5d8: 'v',  # \N{HEBREW LETTER TET}
    0x11706: 'v',  # \N{AHOM LETTER PA}
    0xaba9: 'v',  # \N{CHEROKEE SMALL LETTER DO}
    0x118c0: 'v',  # \N{WARANG CITI SMALL LETTER NGAA}
    0x1d20d: 'V',  # \N{GREEK VOCAL NOTATION SYMBOL-14}
    0x667: 'V',  # \N{ARABIC-INDIC DIGIT SEVEN}
    0x6f7: 'V',  # \N{EXTENDED ARABIC-INDIC DIGIT SEVEN}
    0x2164: 'V',  # \N{ROMAN NUMERAL FIVE}
    0x1d415: 'V',  # \N{MATHEMATICAL BOLD CAPITAL V}
    0x1d449: 'V',  # \N{MATHEMATICAL ITALIC CAPITAL V}
    0x1d47d: 'V',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL V}
    0x1d4b1: 'V',  # \N{MATHEMATICAL SCRIPT CAPITAL V}
    0x1d4e5: 'V',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL V}
    0x1d519: 'V',  # \N{MATHEMATICAL FRAKTUR CAPITAL V}
    0x1d54d: 'V',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL V}
    0x1d581: 'V',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL V}
    0x1d5b5: 'V',  # \N{MATHEMATICAL SANS-SERIF CAPITAL V}
    0x1d5e9: 'V',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL V}
    0x1d61d: 'V',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL V}
    0x1d651: 'V',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL V}
    0x1d685: 'V',  # \N{MATHEMATICAL MONOSPACE CAPITAL V}
    0x474: 'V',  # \N{CYRILLIC CAPITAL LETTER IZHITSA}
    0x2d38: 'V',  # \N{TIFINAGH LETTER YADH}
    0x13d9: 'V',  # \N{CHEROKEE LETTER DO}
    0x142f: 'V',  # \N{CANADIAN SYLLABICS PE}
    0xa6df: 'V',  # \N{BAMUM LETTER KO}
    0xa4e6: 'V',  # \N{LISU LETTER HA}
    0x16f08: 'V',  # \N{MIAO LETTER VA}
    0x118a0: 'V',  # \N{WARANG CITI CAPITAL LETTER NGAA}
    0x1051d: 'V',  # \N{ELBASAN LETTER TE}
    0x1f76c: 'VB',  # \N{ALCHEMICAL SYMBOL FOR BATH OF VAPOURS}
    0x2175: 'vi',  # \N{SMALL ROMAN NUMERAL SIX}
    0x2176: 'vii',  # \N{SMALL ROMAN NUMERAL SEVEN}
    0x2177: 'viii',  # \N{SMALL ROMAN NUMERAL EIGHT}
    0x2165: 'Vl',  # \N{ROMAN NUMERAL SIX}
    0x2166: 'Vll',  # \N{ROMAN NUMERAL SEVEN}
    0x2167: 'Vlll',  # \N{ROMAN NUMERAL EIGHT}
    0x26f: 'w',  # \N{LATIN SMALL LETTER TURNED M}
    0x1d430: 'w',  # \N{MATHEMATICAL BOLD SMALL W}
    0x1d464: 'w',  # \N{MATHEMATICAL ITALIC SMALL W}
    0x1d498: 'w',  # \N{MATHEMATICAL BOLD ITALIC SMALL W}
    0x1d4cc: 'w',  # \N{MATHEMATICAL SCRIPT SMALL W}
    0x1d500: 'w',  # \N{MATHEMATICAL BOLD SCRIPT SMALL W}
    0x1d534: 'w',  # \N{MATHEMATICAL FRAKTUR SMALL W}
    0x1d568: 'w',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL W}
    0x1d59c: 'w',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL W}
    0x1d5d0: 'w',  # \N{MATHEMATICAL SANS-SERIF SMALL W}
    0x1d604: 'w',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL W}
    0x1d638: 'w',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL W}
    0x1d66c: 'w',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL W}
    0x1d6a0: 'w',  # \N{MATHEMATICAL MONOSPACE SMALL W}
    0x1d21: 'w',  # \N{LATIN LETTER SMALL CAPITAL W}
    0x461: 'w',  # \N{CYRILLIC SMALL LETTER OMEGA}
    0x51d: 'w',  # \N{CYRILLIC SMALL LETTER WE}
    0x561: 'w',  # \N{ARMENIAN SMALL LETTER AYB}
    0x1170a: 'w',  # \N{AHOM LETTER JA}
    0x1170e: 'w',  # \N{AHOM LETTER LA}
    0x1170f: 'w',  # \N{AHOM LETTER SA}
    0xab83: 'w',  # \N{CHEROKEE SMALL LETTER LA}
    0x118ef: 'W',  # \N{WARANG CITI NUMBER SIXTY}
    0x118e6: 'W',  # \N{WARANG CITI DIGIT SIX}
    0x1d416: 'W',  # \N{MATHEMATICAL BOLD CAPITAL W}
    0x1d44a: 'W',  # \N{MATHEMATICAL ITALIC CAPITAL W}
    0x1d47e: 'W',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL W}
    0x1d4b2: 'W',  # \N{MATHEMATICAL SCRIPT CAPITAL W}
    0x1d4e6: 'W',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL W}
    0x1d51a: 'W',  # \N{MATHEMATICAL FRAKTUR CAPITAL W}
    0x1d54e: 'W',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL W}
    0x1d582: 'W',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL W}
    0x1d5b6: 'W',  # \N{MATHEMATICAL SANS-SERIF CAPITAL W}
    0x1d5ea: 'W',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL W}
    0x1d61e: 'W',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL W}
    0x1d652: 'W',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL W}
    0x1d686: 'W',  # \N{MATHEMATICAL MONOSPACE CAPITAL W}
    0x51c: 'W',  # \N{CYRILLIC CAPITAL LETTER WE}
    0x13b3: 'W',  # \N{CHEROKEE LETTER LA}
    0x13d4: 'W',  # \N{CHEROKEE LETTER TA}
    0xa4ea: 'W',  # \N{LISU LETTER WA}
    0x166e: 'x',  # \N{CANADIAN SYLLABICS FULL STOP}
    0xd7: 'x',  # \N{MULTIPLICATION SIGN}
    0x292b: 'x',  # \N{RISING DIAGONAL CROSSING FALLING DIAGONAL}
    0x292c: 'x',  # \N{FALLING DIAGONAL CROSSING RISING DIAGONAL}
    0x2a2f: 'x',  # \N{VECTOR OR CROSS PRODUCT}
    0xff58: 'x',  # \N{FULLWIDTH LATIN SMALL LETTER X}
    0x2179: 'x',  # \N{SMALL ROMAN NUMERAL TEN}
    0x1d431: 'x',  # \N{MATHEMATICAL BOLD SMALL X}
    0x1d465: 'x',  # \N{MATHEMATICAL ITALIC SMALL X}
    0x1d499: 'x',  # \N{MATHEMATICAL BOLD ITALIC SMALL X}
    0x1d4cd: 'x',  # \N{MATHEMATICAL SCRIPT SMALL X}
    0x1d501: 'x',  # \N{MATHEMATICAL BOLD SCRIPT SMALL X}
    0x1d535: 'x',  # \N{MATHEMATICAL FRAKTUR SMALL X}
    0x1d569: 'x',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL X}
    0x1d59d: 'x',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL X}
    0x1d5d1: 'x',  # \N{MATHEMATICAL SANS-SERIF SMALL X}
    0x1d605: 'x',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL X}
    0x1d639: 'x',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL X}
    0x1d66d: 'x',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL X}
    0x1d6a1: 'x',  # \N{MATHEMATICAL MONOSPACE SMALL X}
    0x445: 'x',  # \N{CYRILLIC SMALL LETTER HA}
    0x1541: 'x',  # \N{CANADIAN SYLLABICS SAYISI YI}
    0x157d: 'x',  # \N{CANADIAN SYLLABICS HK}
    0x166d: 'X',  # \N{CANADIAN SYLLABICS CHI SIGN}
    0x2573: 'X',  # \N{BOX DRAWINGS LIGHT DIAGONAL CROSS}
    0x10322: 'X',  # \N{OLD ITALIC NUMERAL TEN}
    0x118ec: 'X',  # \N{WARANG CITI NUMBER THIRTY}
    0xff38: 'X',  # \N{FULLWIDTH LATIN CAPITAL LETTER X}
    0x2169: 'X',  # \N{ROMAN NUMERAL TEN}
    0x1d417: 'X',  # \N{MATHEMATICAL BOLD CAPITAL X}
    0x1d44b: 'X',  # \N{MATHEMATICAL ITALIC CAPITAL X}
    0x1d47f: 'X',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL X}
    0x1d4b3: 'X',  # \N{MATHEMATICAL SCRIPT CAPITAL X}
    0x1d4e7: 'X',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL X}
    0x1d51b: 'X',  # \N{MATHEMATICAL FRAKTUR CAPITAL X}
    0x1d54f: 'X',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL X}
    0x1d583: 'X',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL X}
    0x1d5b7: 'X',  # \N{MATHEMATICAL SANS-SERIF CAPITAL X}
    0x1d5eb: 'X',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL X}
    0x1d61f: 'X',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL X}
    0x1d653: 'X',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL X}
    0x1d687: 'X',  # \N{MATHEMATICAL MONOSPACE CAPITAL X}
    0xa7b3: 'X',  # \N{LATIN CAPITAL LETTER CHI}
    0x3a7: 'X',  # \N{GREEK CAPITAL LETTER CHI}
    0x1d6be: 'X',  # \N{MATHEMATICAL BOLD CAPITAL CHI}
    0x1d6f8: 'X',  # \N{MATHEMATICAL ITALIC CAPITAL CHI}
    0x1d732: 'X',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL CHI}
    0x1d76c: 'X',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL CHI}
    0x1d7a6: 'X',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL CHI}
    0x2cac: 'X',  # \N{COPTIC CAPITAL LETTER KHI}
    0x425: 'X',  # \N{CYRILLIC CAPITAL LETTER HA}
    0x2d5d: 'X',  # \N{TIFINAGH LETTER YATH}
    0x16b7: 'X',  # \N{RUNIC LETTER GEBO GYFU G}
    0xa4eb: 'X',  # \N{LISU LETTER SHA}
    0x10290: 'X',  # \N{LYCIAN LETTER MM}
    0x102b4: 'X',  # \N{CARIAN LETTER X}
    0x10317: 'X',  # \N{OLD ITALIC LETTER EKS}
    0x10527: 'X',  # \N{ELBASAN LETTER KHE}
    0x217a: 'xi',  # \N{SMALL ROMAN NUMERAL ELEVEN}
    0x217b: 'xii',  # \N{SMALL ROMAN NUMERAL TWELVE}
    0x216a: 'Xl',  # \N{ROMAN NUMERAL ELEVEN}
    0x216b: 'Xll',  # \N{ROMAN NUMERAL TWELVE}
    0x263: 'y',  # \N{LATIN SMALL LETTER GAMMA}
    0x1d8c: 'y',  # \N{LATIN SMALL LETTER V WITH PALATAL HOOK}
    0xff59: 'y',  # \N{FULLWIDTH LATIN SMALL LETTER Y}
    0x1d432: 'y',  # \N{MATHEMATICAL BOLD SMALL Y}
    0x1d466: 'y',  # \N{MATHEMATICAL ITALIC SMALL Y}
    0x1d49a: 'y',  # \N{MATHEMATICAL BOLD ITALIC SMALL Y}
    0x1d4ce: 'y',  # \N{MATHEMATICAL SCRIPT SMALL Y}
    0x1d502: 'y',  # \N{MATHEMATICAL BOLD SCRIPT SMALL Y}
    0x1d536: 'y',  # \N{MATHEMATICAL FRAKTUR SMALL Y}
    0x1d56a: 'y',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL Y}
    0x1d59e: 'y',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL Y}
    0x1d5d2: 'y',  # \N{MATHEMATICAL SANS-SERIF SMALL Y}
    0x1d606: 'y',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL Y}
    0x1d63a: 'y',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL Y}
    0x1d66e: 'y',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Y}
    0x1d6a2: 'y',  # \N{MATHEMATICAL MONOSPACE SMALL Y}
    0x28f: 'y',  # \N{LATIN LETTER SMALL CAPITAL Y}
    0x1eff: 'y',  # \N{LATIN SMALL LETTER Y WITH LOOP}
    0xab5a: 'y',  # \N{LATIN SMALL LETTER Y WITH SHORT RIGHT LEG}
    0x3b3: 'y',  # \N{GREEK SMALL LETTER GAMMA}
    0x213d: 'y',  # \N{DOUBLE-STRUCK SMALL GAMMA}
    0x1d6c4: 'y',  # \N{MATHEMATICAL BOLD SMALL GAMMA}
    0x1d6fe: 'y',  # \N{MATHEMATICAL ITALIC SMALL GAMMA}
    0x1d738: 'y',  # \N{MATHEMATICAL BOLD ITALIC SMALL GAMMA}
    0x1d772: 'y',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL GAMMA}
    0x1d7ac: 'y',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL GAMMA}
    0x443: 'y',  # \N{CYRILLIC SMALL LETTER U}
    0x4af: 'y',  # \N{CYRILLIC SMALL LETTER STRAIGHT U}
    0x10e7: 'y',  # \N{GEORGIAN LETTER QAR}
    0x118dc: 'y',  # \N{WARANG CITI SMALL LETTER HAR}
    0xff39: 'Y',  # \N{FULLWIDTH LATIN CAPITAL LETTER Y}
    0x1d418: 'Y',  # \N{MATHEMATICAL BOLD CAPITAL Y}
    0x1d44c: 'Y',  # \N{MATHEMATICAL ITALIC CAPITAL Y}
    0x1d480: 'Y',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL Y}
    0x1d4b4: 'Y',  # \N{MATHEMATICAL SCRIPT CAPITAL Y}
    0x1d4e8: 'Y',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL Y}
    0x1d51c: 'Y',  # \N{MATHEMATICAL FRAKTUR CAPITAL Y}
    0x1d550: 'Y',  # \N{MATHEMATICAL DOUBLE-STRUCK CAPITAL Y}
    0x1d584: 'Y',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL Y}
    0x1d5b8: 'Y',  # \N{MATHEMATICAL SANS-SERIF CAPITAL Y}
    0x1d5ec: 'Y',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL Y}
    0x1d620: 'Y',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL Y}
    0x1d654: 'Y',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Y}
    0x1d688: 'Y',  # \N{MATHEMATICAL MONOSPACE CAPITAL Y}
    0x3a5: 'Y',  # \N{GREEK CAPITAL LETTER UPSILON}
    0x3d2: 'Y',  # \N{GREEK UPSILON WITH HOOK SYMBOL}
    0x1d6bc: 'Y',  # \N{MATHEMATICAL BOLD CAPITAL UPSILON}
    0x1d6f6: 'Y',  # \N{MATHEMATICAL ITALIC CAPITAL UPSILON}
    0x1d730: 'Y',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL UPSILON}
    0x1d76a: 'Y',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL UPSILON}
    0x1d7a4: 'Y',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL UPSILON}
    0x2ca8: 'Y',  # \N{COPTIC CAPITAL LETTER UA}
    0x423: 'Y',  # \N{CYRILLIC CAPITAL LETTER U}
    0x4ae: 'Y',  # \N{CYRILLIC CAPITAL LETTER STRAIGHT U}
    0x13a9: 'Y',  # \N{CHEROKEE LETTER GI}
    0x13bd: 'Y',  # \N{CHEROKEE LETTER MU}
    0xa4ec: 'Y',  # \N{LISU LETTER YA}
    0x16f43: 'Y',  # \N{MIAO LETTER AH}
    0x118a4: 'Y',  # \N{WARANG CITI CAPITAL LETTER YA}
    0x102b2: 'Y',  # \N{CARIAN LETTER U}
    0x1d433: 'z',  # \N{MATHEMATICAL BOLD SMALL Z}
    0x1d467: 'z',  # \N{MATHEMATICAL ITALIC SMALL Z}
    0x1d49b: 'z',  # \N{MATHEMATICAL BOLD ITALIC SMALL Z}
    0x1d4cf: 'z',  # \N{MATHEMATICAL SCRIPT SMALL Z}
    0x1d503: 'z',  # \N{MATHEMATICAL BOLD SCRIPT SMALL Z}
    0x1d537: 'z',  # \N{MATHEMATICAL FRAKTUR SMALL Z}
    0x1d56b: 'z',  # \N{MATHEMATICAL DOUBLE-STRUCK SMALL Z}
    0x1d59f: 'z',  # \N{MATHEMATICAL BOLD FRAKTUR SMALL Z}
    0x1d5d3: 'z',  # \N{MATHEMATICAL SANS-SERIF SMALL Z}
    0x1d607: 'z',  # \N{MATHEMATICAL SANS-SERIF BOLD SMALL Z}
    0x1d63b: 'z',  # \N{MATHEMATICAL SANS-SERIF ITALIC SMALL Z}
    0x1d66f: 'z',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Z}
    0x1d6a3: 'z',  # \N{MATHEMATICAL MONOSPACE SMALL Z}
    0x1d22: 'z',  # \N{LATIN LETTER SMALL CAPITAL Z}
    0xab93: 'z',  # \N{CHEROKEE SMALL LETTER NO}
    0x118c4: 'z',  # \N{WARANG CITI SMALL LETTER YA}
    0x102f5: 'Z',  # \N{COPTIC EPACT NUMBER THREE HUNDRED}
    0x118e5: 'Z',  # \N{WARANG CITI DIGIT FIVE}
    0xff3a: 'Z',  # \N{FULLWIDTH LATIN CAPITAL LETTER Z}
    0x2124: 'Z',  # \N{DOUBLE-STRUCK CAPITAL Z}
    0x2128: 'Z',  # \N{BLACK-LETTER CAPITAL Z}
    0x1d419: 'Z',  # \N{MATHEMATICAL BOLD CAPITAL Z}
    0x1d44d: 'Z',  # \N{MATHEMATICAL ITALIC CAPITAL Z}
    0x1d481: 'Z',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL Z}
    0x1d4b5: 'Z',  # \N{MATHEMATICAL SCRIPT CAPITAL Z}
    0x1d4e9: 'Z',  # \N{MATHEMATICAL BOLD SCRIPT CAPITAL Z}
    0x1d585: 'Z',  # \N{MATHEMATICAL BOLD FRAKTUR CAPITAL Z}
    0x1d5b9: 'Z',  # \N{MATHEMATICAL SANS-SERIF CAPITAL Z}
    0x1d5ed: 'Z',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL Z}
    0x1d621: 'Z',  # \N{MATHEMATICAL SANS-SERIF ITALIC CAPITAL Z}
    0x1d655: 'Z',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Z}
    0x1d689: 'Z',  # \N{MATHEMATICAL MONOSPACE CAPITAL Z}
    0x396: 'Z',  # \N{GREEK CAPITAL LETTER ZETA}
    0x1d6ad: 'Z',  # \N{MATHEMATICAL BOLD CAPITAL ZETA}
    0x1d6e7: 'Z',  # \N{MATHEMATICAL ITALIC CAPITAL ZETA}
    0x1d721: 'Z',  # \N{MATHEMATICAL BOLD ITALIC CAPITAL ZETA}
    0x1d75b: 'Z',  # \N{MATHEMATICAL SANS-SERIF BOLD CAPITAL ZETA}
    0x1d795: 'Z',  # \N{MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ZETA}
    0x13c3: 'Z',  # \N{CHEROKEE LETTER NO}
    0xa4dc: 'Z',  # \N{LISU LETTER DZA}
    0x118a9: 'Z',  # \N{WARANG CITI CAPITAL LETTER O}
}
