[tool.poetry]
name = "redlock-plus"
version = "0.1.6"
description = "Distributed locks with Redis"
authors = [
  "Janek Nouvertné <provinzkraut@posteo.de>",
  "Leonardo Zhou <glasslion@gmail.com>",
]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/provinzkraut/redlock-plus"
repository = "https://github.com/provinzkraut/redlock-plus"
documentation = "https://redlock-plus.readthedocs.io/en/latest/"
keywords = ["redlock", "redis", "lock", "distributed"]
classifiers = [
  'Development Status :: 5 - Production/Stable',
  'Intended Audience :: Developers',
  'License :: OSI Approved :: MIT License',
  'Programming Language :: Python :: 3.7',
  'Programming Language :: Python :: 3.8',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: Implementation :: CPython',
  'Programming Language :: Python :: Implementation :: PyPy'
]
packages = [
  { include = "redlock_plus.py" }
]

[tool.poetry.dependencies]
python = ">=3.7"
redis = "^4.0.2"
importlib-metadata = {version = "<4.3", python = "<3.8"}

## docs section
Sphinx = {version = "^4.3.1", optional = true}
sphinx-autodoc-typehints = {version = "^1.12.0", markers = "platform_python_implementation == 'CPython'", optional = true}


[tool.poetry.group.dev.dependencies]
pytest = "^6.2.5"
black = "^21.12-beta.0"
coverage = "^6.2"
fakeredis = "^1.7.0"
lupa = "^1.10"
pytest-mock = "^3.6.1"
pytest-cov = "^3.0.0"
mypy = "^0.920"
flake8 = "^4.0.1"
types-redis = "^4.0.4"


[tool.poetry.extras]
docs = ["sphinx", "sphinx-autodoc-typehints"]

[tool.pytest.ini_options]
console_output_style = "count"
markers = [
  "slow: this test is slow",
  "py_version: run only if the version requirements are met"
  ]
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
