
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-14T20:51:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "295714100529afe92abe5add435e485a8e14104f",
 "version": "v2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
