import pygame

EVENT_PLAYER_1 = pygame.USEREVENT + 1
EVENT_PLAYER_2 = pygame.USEREVENT + 2
EVENT_PLAYER_3 = pygame.USEREVENT + 3
EVENT_PLAYER_4 = pygame.USEREVENT + 4

ALL_PLAYER_EVENT_TYPES = [
    EVENT_PLAYER_1, EVENT_PLAYER_2, EVENT_PLAYER_3, EVENT_PLAYER_4
]
