[[character]]
  name = "reimu"
  display_name = "博丽灵梦"
  hp = 20
  atk = 256

  [[character.spellcard]]
    name = "reimu_0"
    display_name = "[灵符] 梦想封印"
    harm = [0, 4]
    atk = [0, 0]
    shield = 0
    hp = 0

  [[character.spellcard]]
    name = "reimu_1"
    display_name = "梦想天生"
    harm = [3, 4]
    atk = [50, 2]
    shield = 1
    hp = 0

  [[character.spellcard]]
    name = "reimu_2"
    display_name = "[梦符] 封魔阵"
    harm = [0, 4]
    atk = [0, 0]
    shield = 1
    hp = 0
  
[[character]]
  name = "marisa"
  display_name = "雾雨魔理沙"
  atk = 300
  hp = 18

  [[character.spellcard]]
    name = "marisa_0"
    display_name = "[恋符] Master Spark"
    harm = [1, 4]
    atk = [0, 0]
    shield = 0
    hp = 0
  
  [[character.spellcard]]
    name = "marisa_1"
    display_name = "[魔符] 星尘幻想"
    harm = [0, 3]
    atk = [0, 0]
    shield = 1
    hp = 1



    