[tool.poetry]
name = "ziz"
version = "0.0.1"
description = " "
authors = ["Erik Li"]
packages = [
    { include = "cicd_example" },
]

[tool.poetry.dependencies]
python = "^3.5"
pytest = "6.1.2"
"requests[security]" = "2.25.1"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[[tool.poetry.source]]
name = "xpev_nexus"
url = "http://nexus-ht.xiaopeng.link:8081/repository/ai_infra_pypi/"
