[tool.poetry]
name = "calculadora_varanda"
version = "0.0.1"
description = "Está é uma calculadora mantida pela Codaqui."
authors = ["Pedro Varanda"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"