repos:
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort
        # args: ["--profile", "black", "--filter-files"]
        additional_dependencies: [toml]
        files: \.py$
        language_version: python3.8

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3.8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--disallow-untyped-defs, --disallow-untyped-calls, --check-untyped-defs]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
