[tool.poetry]
name = "streamlit_stackoverflow"
version = "0.1.0"
description = "Project created to learning Streamlit."
authors = ["Joao Corte <jpaulorc@gmail.com>"]
exclude = ["streamlit_stackoverflow/.git"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
streamlit = "^1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
