[tool.poetry]
name = "shuncommands"
version = "1.0.3"
description = "mypaceshun usefull commands"
authors = ["KAWAI Shun <mypaceshun@gmail.com>"]
maintainers = ["KAWAI Shun <mypaceshun@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/mypaceshun/shuncommands"
repository = "https://github.com/mypaceshun/shuncommands"
keywords = ["python", "click"]
packages = [
  {include = 'src/'}
]
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0"
gitignore-parser = "^0.0.8"
pikepdf = "^4.1.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
poethepoet = "^0.11.0"
flake8 = "^4.0.1"
autoflake = "^1.4"
autopep8 = "^1.6.0"
isort = "^5.10.1"
git-changelog = "^0.5.0"

[tool.poetry.scripts]
rmtmp = "src.rmtmp:ctx"
pdftool = "src.pdftool:ctx"

[tool.poe.tasks.changelog]
cmd = "git-changelog -o CHANGELOG.md .git"

[tool.poe.tasks.lint]
cmd = "flake8 src/"

[tool.poe.tasks.format]
sequence = [
  { cmd = "autopep8 -ir src/" },
  { cmd = "autoflake -ir --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports src/" },
  { cmd = "isort src/" }
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
