[tool.poetry]
name = "linz_logger"
version = "0.6.0"
description = "LINZ standard Logging format"
authors = ["Blayne <bchard@linz.govt.nz>", "Megan <mdavidson@linz.govt.nz>"]
license = "MIT"

readme = "README.md"

repository = "https://github.com/linz/python-linz-logger"

keywords = ["LINZ", "logging"]

[tool.poetry.dependencies]
python = "^3.7"
structlog = "^20.1.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.8.0"
pylint = "^2.7.4"
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 127

[tool.isort]
line_length = 127
case_sensitive = true
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3
force_grid_wrap = 0
