[tool.poetry]
name = "pyGun"
version = "0.0.1a0"
description = "Gun"
authors = ["n2k3 <n2k3@pm.me>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
