
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-15T05:10:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "97d39b2666a4e40183a99683ddb731f0ab2ce125",
 "version": "1.15.0.post.dev864"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
