[tool.poetry]
name = "concatenate"
version = "0.1.1"
description = "Concatenate two objects of the same type"
authors = ["Tom Bulled <26026015+tombulled@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tombulled/concatenate"
repository = "https://github.com/tombulled/concatenate"
keywords = ["python", "concatenate", "join"]

[tool.poetry.dependencies]
python = "^3.9"
registrate = "^0.1.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
