# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loopgrpc/compiled/debug.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loopgrpc/compiled/debug.proto',
  package='looprpc',
  syntax='proto3',
  serialized_options=b'Z%github.com/lightninglabs/loop/looprpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dloopgrpc/compiled/debug.proto\x12\x07looprpc\"\x16\n\x14\x46orceAutoLoopRequest\"\x17\n\x15\x46orceAutoLoopResponse2W\n\x05\x44\x65\x62ug\x12N\n\rForceAutoLoop\x12\x1d.looprpc.ForceAutoLoopRequest\x1a\x1e.looprpc.ForceAutoLoopResponseB\'Z%github.com/lightninglabs/loop/looprpcb\x06proto3'
)




_FORCEAUTOLOOPREQUEST = _descriptor.Descriptor(
  name='ForceAutoLoopRequest',
  full_name='looprpc.ForceAutoLoopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=64,
)


_FORCEAUTOLOOPRESPONSE = _descriptor.Descriptor(
  name='ForceAutoLoopResponse',
  full_name='looprpc.ForceAutoLoopResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['ForceAutoLoopRequest'] = _FORCEAUTOLOOPREQUEST
DESCRIPTOR.message_types_by_name['ForceAutoLoopResponse'] = _FORCEAUTOLOOPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForceAutoLoopRequest = _reflection.GeneratedProtocolMessageType('ForceAutoLoopRequest', (_message.Message,), {
  'DESCRIPTOR' : _FORCEAUTOLOOPREQUEST,
  '__module__' : 'loopgrpc.compiled.debug_pb2'
  # @@protoc_insertion_point(class_scope:looprpc.ForceAutoLoopRequest)
  })
_sym_db.RegisterMessage(ForceAutoLoopRequest)

ForceAutoLoopResponse = _reflection.GeneratedProtocolMessageType('ForceAutoLoopResponse', (_message.Message,), {
  'DESCRIPTOR' : _FORCEAUTOLOOPRESPONSE,
  '__module__' : 'loopgrpc.compiled.debug_pb2'
  # @@protoc_insertion_point(class_scope:looprpc.ForceAutoLoopResponse)
  })
_sym_db.RegisterMessage(ForceAutoLoopResponse)


DESCRIPTOR._options = None

_DEBUG = _descriptor.ServiceDescriptor(
  name='Debug',
  full_name='looprpc.Debug',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=91,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='ForceAutoLoop',
    full_name='looprpc.Debug.ForceAutoLoop',
    index=0,
    containing_service=None,
    input_type=_FORCEAUTOLOOPREQUEST,
    output_type=_FORCEAUTOLOOPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEBUG)

DESCRIPTOR.services_by_name['Debug'] = _DEBUG

# @@protoc_insertion_point(module_scope)
