[tool.poetry]
name = "watchmen-boot"
version = "15.1.10"
description = ""
authors = ["luke0623 <luke0623@outlook.com>"]


packages = [
    { include = "watchmen" }
]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8.2"
pymongo = "^3.11.4"
cx-Oracle = "^8.2.1"
arrow = "^1.1.0"
cacheout = "^0.13.1"
mysqlclient = "^2.1.0"
SQLAlchemy = "^1.4.27"
requests = "^2.25.1"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
