# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import common_pb2 as common__pb2
from . import imu_pb2 as imu__pb2


class MagnetometerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMagnetometerMetadata = channel.unary_unary(
                '/mobot.Magnetometer/SetMagnetometerMetadata',
                request_serializer=imu__pb2.SensorMetadata.SerializeToString,
                response_deserializer=common__pb2.Success.FromString,
                )
        self.NewMagnetometerData = channel.unary_unary(
                '/mobot.Magnetometer/NewMagnetometerData',
                request_serializer=common__pb2.Quaternion.SerializeToString,
                response_deserializer=common__pb2.Success.FromString,
                )


class MagnetometerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetMagnetometerMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewMagnetometerData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MagnetometerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMagnetometerMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMagnetometerMetadata,
                    request_deserializer=imu__pb2.SensorMetadata.FromString,
                    response_serializer=common__pb2.Success.SerializeToString,
            ),
            'NewMagnetometerData': grpc.unary_unary_rpc_method_handler(
                    servicer.NewMagnetometerData,
                    request_deserializer=common__pb2.Quaternion.FromString,
                    response_serializer=common__pb2.Success.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mobot.Magnetometer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Magnetometer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetMagnetometerMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mobot.Magnetometer/SetMagnetometerMetadata',
            imu__pb2.SensorMetadata.SerializeToString,
            common__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewMagnetometerData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mobot.Magnetometer/NewMagnetometerData',
            common__pb2.Quaternion.SerializeToString,
            common__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)