[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | amber.*
)/
'''
[build-system]
requires = ["setuptools>=58", "wheel"]
build-backend = "setuptools.build_meta" # maybe poetry in the future
