[dependencies]
ndarray = "0.15.3"
numpy = "0.14.1"

[dependencies.changeforest]
path = "local_dependencies/changeforest"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.14.5"

[lib]
crate-type = ["cdylib"]
name = "changeforest"

[package]
edition = "2018"
name = "changeforest_py"
version = "0.2.1"
[package.metadata.maturin]
name = "changeforest"
