from http.server import BaseHTTPRequestHandler, HTTPServer
from typing import Any
from wsgiref.handlers import SimpleHandler

class ServerHandler(SimpleHandler):
    server_software: Any
    def close(self) -> None: ...

class WSGIServer(HTTPServer):
    application: Any
    def server_bind(self) -> None: ...
    def setup_environ(self) -> None: ...
    def get_app(self): ...
    def set_app(self, application) -> None: ...

class WSGIRequestHandler(BaseHTTPRequestHandler):
    server_version: Any
    def get_environ(self): ...
    def get_stderr(self): ...
    raw_requestline: Any
    requestline: str
    request_version: str
    command: str
    def handle(self) -> None: ...

def demo_app(environ, start_response): ...
def make_server(host, port, app, server_class=..., handler_class=...): ...
