[tool.poetry]
name = "racetrackgym"
version = "0.1.4"
description = "Python Simulation of the Racetrack game. This implementation is compatible with the OpenAI Gym API, and comes with additional extensions"
authors = ["Timo P. Gros <timopgros@cs.uni-saarland.de>"]
readme = "README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
argparse = "^1.4.0"
numpy = "^1.21.4"
rlmate = "*"
Pillow = "^8.4.0"
matplotlib = "^3.4.3"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.2"
pep8-naming = "^0.9.1"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
