[tool.poetry]
name = "intell"
version = "1.0.0"
description = "Make a functional code start!"
authors = ["OwoNicoo <86409467+DiscordBotML@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
