
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-19T16:16:39-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f533ebb5f705d3786f0694c49a64843476a9826",
 "version": "2.1.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
