[tool.poetry]
name = "ssh_api"
version = "1.0.0"
description = "ssh api for make a ssh client's or code.... Main platform is windows 10,11."
authors = ["OwoNicoo <86409467+DiscordBotML@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
