[tool.poetry]
name = "kghub-downloader"
version = "0.1.2"
description = "Downloads and caches files for knowledge graph ETL"
authors = ["The Monarch Initiative <info@monarchinitiative.org>"]

[tool.poetry.dependencies]
python = ">=3.7, <3.10"
elasticsearch = "^>7.0, <9.0"
compress-json = ">1.0, <2.0"
PyYAML = ">5.0,<7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
