{% set name = "crabnet" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crabnet-{{ version }}.tar.gz
  sha256: 1768ea2f597f531abd783ebbec67c9c2038502ab60eafdc4a056148b1108b478

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.6,<3.10
  run:
    - joblib
    - cudatoolkit <11.4
    - pytorch >=1.9.0
    - matplotlib-base
    - numpy
    - pandas
    - psutil
    - python >=3.6,<3.10
    - scikit-learn
    - scipy
    - seaborn
    - tqdm

test:
  imports:
    - crabnet
    - crabnet.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/crabnet/
  summary: Predict materials properties using only the composition information.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
