[tool.poetry]
name = "searcheonet"
version = "0.1.0"
description = "Python package that allows users to search for information about natural events from the NASA EONET API"
authors = ["Alan Shen"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
