"""
    eHelply SDK

    eHelply SDK  # noqa: E501

    The version of the OpenAPI document: 1.1.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply-python-sdk
from ehelply-python-sdk.model.projects_usage_type_create import ProjectsUsageTypeCreate
globals()['ProjectsUsageTypeCreate'] = ProjectsUsageTypeCreate
from ehelply-python-sdk.model.body_create_usage_type_projects_usage_types_post import BodyCreateUsageTypeProjectsUsageTypesPost


class TestBodyCreateUsageTypeProjectsUsageTypesPost(unittest.TestCase):
    """BodyCreateUsageTypeProjectsUsageTypesPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyCreateUsageTypeProjectsUsageTypesPost(self):
        """Test BodyCreateUsageTypeProjectsUsageTypesPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyCreateUsageTypeProjectsUsageTypesPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
