"""
    eHelply SDK

    eHelply SDK  # noqa: E501

    The version of the OpenAPI document: 1.1.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply-python-sdk
from ehelply-python-sdk.model.create_ticket import CreateTicket
globals()['CreateTicket'] = CreateTicket
from ehelply-python-sdk.model.body_update_ticket_support_projects_project_uuid_members_member_uuid_tickets_ticket_id_put import BodyUpdateTicketSupportProjectsProjectUuidMembersMemberUuidTicketsTicketIdPut


class TestBodyUpdateTicketSupportProjectsProjectUuidMembersMemberUuidTicketsTicketIdPut(unittest.TestCase):
    """BodyUpdateTicketSupportProjectsProjectUuidMembersMemberUuidTicketsTicketIdPut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyUpdateTicketSupportProjectsProjectUuidMembersMemberUuidTicketsTicketIdPut(self):
        """Test BodyUpdateTicketSupportProjectsProjectUuidMembersMemberUuidTicketsTicketIdPut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyUpdateTicketSupportProjectsProjectUuidMembersMemberUuidTicketsTicketIdPut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
