"""
    eHelply SDK

    eHelply SDK  # noqa: E501

    The version of the OpenAPI document: 1.1.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply-python-sdk
from ehelply-python-sdk.model.access_group_create import AccessGroupCreate
globals()['AccessGroupCreate'] = AccessGroupCreate
from ehelply-python-sdk.model.body_create_group_access_partitions_partition_identifier_who_groups_post import BodyCreateGroupAccessPartitionsPartitionIdentifierWhoGroupsPost


class TestBodyCreateGroupAccessPartitionsPartitionIdentifierWhoGroupsPost(unittest.TestCase):
    """BodyCreateGroupAccessPartitionsPartitionIdentifierWhoGroupsPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyCreateGroupAccessPartitionsPartitionIdentifierWhoGroupsPost(self):
        """Test BodyCreateGroupAccessPartitionsPartitionIdentifierWhoGroupsPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyCreateGroupAccessPartitionsPartitionIdentifierWhoGroupsPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
