"""
    eHelply SDK

    eHelply SDK  # noqa: E501

    The version of the OpenAPI document: 1.1.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply-python-sdk
from ehelply-python-sdk.model.alarm_acknowledge import AlarmAcknowledge


class TestAlarmAcknowledge(unittest.TestCase):
    """AlarmAcknowledge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlarmAcknowledge(self):
        """Test AlarmAcknowledge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlarmAcknowledge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
