"""
    eHelply SDK

    eHelply SDK  # noqa: E501

    The version of the OpenAPI document: 1.1.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply-python-sdk
from ehelply-python-sdk.model.projects_usage_type_unit_price import ProjectsUsageTypeUnitPrice
globals()['ProjectsUsageTypeUnitPrice'] = ProjectsUsageTypeUnitPrice
from ehelply-python-sdk.model.projects_usage_type_update import ProjectsUsageTypeUpdate


class TestProjectsUsageTypeUpdate(unittest.TestCase):
    """ProjectsUsageTypeUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectsUsageTypeUpdate(self):
        """Test ProjectsUsageTypeUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectsUsageTypeUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
