fail_fast: true
repos:
-   repo: https://gitee.com/dlzhou_admin/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
#    -   id: flake8
#        exclude: ^tests/

-   repo: https://gitee.com/JimyFengqi/flake8
    rev: 4.0.0  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
#        exclude: ^tests/

-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        args: [ "--profile", "black", "--filter-files" ]

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
