
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-16T18:42:46+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "55d52279747f0a1a0e1db0b1cf39d1e5a3df87e5",
 "version": "1.0.7rc17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
