VERSION_YEAR = 2021
VERSION_MONTH = int('12')
VERSION_DAY = int('14')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('19')
MAJOR_VERSION = 0
MINOR_VERSION = 3
PATCH_VERSION = 202112141219
version_date = '2021/12/14 12:19'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
