name: Build

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # supported python versions can be found here
        # https://github.com/actions/python-versions/releases
        python-version: [3.8, 3.9, 3.10]
    steps:
    - uses: actions/checkout@master
    - name: set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install -U wheel
        pip install -r requirements.txt
        pip install .
    - name: Run mypy
      run: |
          pip install -U mypy
          mypy -p zxcvbn --ignore-missing-imports
    - name: Run tests
      run: |
          pytest -v 
    - name: Test Compatibility
      run: |
          python tests/test_compatibility.py tests/password_expected_value.json
