$schema: http://json-schema.org/draft-07/schema#
$id: kvstore/file
allOf:
- $ref: KvStore
- type: object
  properties:
    driver:
      const: file
    path:
      type: string
      title: Path to root directory on local filesystem.
    file_io_concurrency:
      $ref: ContextResource
      description: >-
        Specifies or references a previously defined
        `Context.file_io_concurrency`.
  required:
  - path
