[build-system]
requires = [
  "setuptools",
  "wheel",
  "numpy==1.15.4; python_version=='3.6'",
  "numpy==1.15.4; python_version=='3.7'",
  "numpy==1.17.5; python_version=='3.8'",
  "numpy==1.19.5; python_version=='3.9'",
  "numpy==1.21.4; python_version=='3.10'",
  "numpy; python_version>'3.10'",
  "Cython>=0.29.24"]

[tool.black]
target-version = ['py37', 'py38', 'py39']
exclude = '''
(
    \.egg
  | \.git
  | \.mypy_cache
  | \.oytest_cache
  | _build
  | buck-out
  | build
  | dist
)
'''
