[tool.poetry]
name = "assert_typecheck"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
mypy = ">=0.800"
ast-compat = "^0.10.1"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
pytest-cov = "^2.10"
flake8 = "*"
isort = "^5.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
