[tool.poetry]
name = "initdb"
version = "0.5.0"
description = "Creates a user and database owned by that user"
authors = ["Eugen Ciur <eugen@papermerge.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.8"
psycopg2 = "^2.9.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
