name: Code Formatting and Linting

on:
  push:
    branches: [ master, dev, 'release/*' ]
  pull_request:
    branches: [ master, dev, 'release/*' ]
  workflow_dispatch:

jobs:
  format_lint_check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      OS: 'ubuntu-latest'
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8
    - name: Test Code Formatting with Black
      run: |
        black --check c3/
    - name: Code Linting with flake8
      run: |
        flake8 --count c3/

