[tool.poetry]
name = "test_poetry_vp"
version = "0.1.0"
description = "test for poetry"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.10"
six = "^1.16.0"
wheel = "^0.37.0"
tzlocal = "^4.1"
PyQt5 = "^5.15.6"
numpy = "^1.21.5"
pyqtgraph = "^0.12.3"
pandas = "^1.3.5"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"
pycryptodome = "^3.12.0"
pyzmq = "^22.3.0"
WMI = "^1.5.1"
QScintilla = "^2.13.1"
plotly = "^5.4.0"
exchange-calendars = "^3.5"
psycopg2-binary = "^2.9.2"
vnpy-rest = "^1.0.3"
vnpy-websocket = "^1.0.2"
vnpy-ctp = "^6.5.1"
vnpy-ctptest = "^6.5.1"
vnpy-xtp = "^2.2.27"
vnpy-tts = "^6.5.1"
vnpy-rohon = "^6.5.1"
vnpy-mini = "^1.5.6"
vnpy-sopt = "^3.5.5"
vnpy-uft = "^3.7.2"
vnpy-esunny = "^1.0.2"
vnpy-ib = "^9.81.1"
vnpy-tap = "^9.0.0"
vnpy-da = "^1.12.0"
vnpy-sgit = "^4.8.2"
vnpy-femas = "^1.0.0"
vnpy-ost = "^2.0.1"
vnpy-tora = "^2021.12.5"
vnpy-ctastrategy = "^1.0.6"
vnpy-ctabacktester = "^1.0.3"
vnpy-riskmanager = "^1.0.2"
vnpy-datamanager = "^1.0.4"
vnpy-webtrader = "^1.0.2"
vnpy-spreadtrading = "^1.1.3"
vnpy-datarecorder = "^1.0.2"
vnpy-chartwizard = "^1.0.1"
vnpy-optionmaster = "^1.0.1"
vnpy-algotrading = "^1.0.1"
vnpy-scripttrader = "^1.0.0"
vnpy-portfoliomanager = "^1.0.0"
vnpy-portfoliostrategy = "^1.0.0"
vnpy-paperaccount = "^1.0.0"
vnpy-sqlite = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
