[tool.poetry]
name = "gengir"
version = "1.0.2"
description = "Generate PEP 561 stubs for the GObject introspection library. Forked from fakegir"
authors = ["Santiago Cézar <santiagocezar2013@gmail.com>"]
repository = "https://github.com/santiagocezar/gengir"
readme = "README.md"
keywords = ["typing", "type hints", "gtk"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
lxml = "^4.6.4"
astor = "^0.8.1"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
bandit = "^1.7.1"
black = {version = "^21.11b1", allow-prereleases = true}
lxml-stubs = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gengir = "gengir.cli:run_cli"