# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - ".cache/pip"
before_script:
  - echo "Test Run by $GITLAB_USER_LOGIN in branch $CI_COMMIT_BRANCH"
  - python -V
  - pip install -r requirements.txt
stages:
  - validate
  - security
  - test
  - deploy
pep8_check_style:
  tags:
    - docker
  image: python:3.8
  stage: validate
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - pycodestyle --show-source --show-pep8 --exclude="docs,venv,.eggs,versioneer.py,build"
unit_tests_3.8:
  tags:
    - docker
  image: python:3.8
  stage: test
  before_script:
    - pip install -r requirements.txt -r requirements-dev.txt
  script:
    - coverage run --include 'drb/*'  --omit drb/_version.py  -m unittest -v
    - coverage xml
    - coverage report
    - coverage-badge
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    reports:
      cobertura: coverage.xml
unit_tests_3.9:
  tags:
    - docker
  image: python:3.9
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest -v
release:
  tags:
    - docker
  image: python:3.8
  stage: deploy
  before_script:
    - pip install -r requirements.txt -r requirements-dev.txt
  script:
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - tags

pages:
  stage: deploy
  image: python:3.8
  before_script:
    - pip install -r requirements.txt -r requirements-doc.txt
  script:
    - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
    - tags

sast:
  stage: security
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
