[tool.poetry]
name = "zack_puc_ia_csv_converter"
version = "0.1.7"
description = "Convert CSV to JSON or JSON to CSV"
authors = ["ezequiel lima  <ezekiel_lima@hotmail.com>"]
readme= "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.5"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
mypy = "^0.910"
black = "^21.12b0"
isort = "^5.10.1"
pandas-stubs = "^1.2.0"
ipython = "^7.30.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length=99

[tool.isort]
profile="black"

[tool.poetry.scripts]
csv_converter = 'zack_puc_ia_csv_converter.converter:converter'