name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install pipenv
        run: |
          python -m pip install pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --dev --pre
      - name: Run tests with pytest
        run: pipenv run python -m pytest
      - name: Check format
        run: pipenv run python -m black --check --diff .
      - name: Run flake8
        run: find ovs_dbg -iname "*.py" | xargs pipenv run python -m flake8
