[project]
name = "anyforce"
version = "0.12.7"
description = ""
dependencies = [ "fastapi~=0.70.0", "uvicorn[standard]~=0.15.0", "pydantic[email]~=1.8.2", "python-jose[cryptography]~=3.3.0", "tortoise-orm~=0.17.8", "passlib[bcrypt]~=1.7.4", "requests~=2.26.0", "types-requests~=2.25.12", "orjson~=3.6.4", "python-json-logger~=2.0.2", "Jinja2~=3.0.3", "colorama~=0.4.4", "aiohttp~=3.8.1", "starlette-context~=0.3.3", "itsdangerous~=2.0.1", "inflection~=0.5.1", "aenum~=3.1.5",]
requires-python = ">=3.8"
[[project.authors]]
name = "exherb"
email = "i@4leaf.me"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "COPYRIGHT"

[project.urls]
homepage = "https://github.com/42signal/anyforce"

[project.optional-dependencies]

[tool.pdm]
includes = [ "anyforce/**/*.py", "anyforce/py.typed", "README.md",]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
verify_ssl = true

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3

[tool.pdm.dev-dependencies]
dev = [ "flake8~=4.0.1", "isort~=5.10.1", "black~=21.10b0", "pytest~=6.2.5", "typer~=0.4.0", "pytest-asyncio~=0.16.0", "Faker~=9.8.2", "pytest-cov~=3.0.0", "twine~=3.5.0",]

[tool.pytest.ini_options]
testpaths = [ "tests",]
