[tool.poetry]
name = "pyobs-pilar"
version = "0.15.0-alpha.3"
description = "pyobs model for Pilar TCS"
authors = ["Tim-Oliver Husser <thusser@uni-goettingen.de>"]
license = "MIT"

[tool.poetry.dependencies]

[tool.poetry.dev-dependencies]
python = ">=3.7,<3.11"
astropy = "^4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
