"""
    Gr4vy API

    Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.  # noqa: E501

    The version of the OpenAPI document: 1.1.0-beta
    Contact: code@gr4vy.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.error_detail import ErrorDetail
globals()['ErrorDetail'] = ErrorDetail
from openapi_client.model.error403_forbidden import Error403Forbidden


class TestError403Forbidden(unittest.TestCase):
    """Error403Forbidden unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testError403Forbidden(self):
        """Test Error403Forbidden"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Error403Forbidden()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
