from .generic import Manager as Manager

class BusinessUsersManager(Manager):
    def invite(self, email_list): ...
    def accept_invitation(self, id, secret): ...
    def reject_invitation(self, id, secret): ...
