from .. import models as models
from .generic import AllMixin as AllMixin
from .generic import GetByIdMixin as GetByIdMixin
from .generic import Manager as Manager
from .generic import SyncMixin as SyncMixin

class SectionsManager(Manager, AllMixin, GetByIdMixin, SyncMixin):
    state_name: str
    object_type: str
    def add(self, name, project_id, **kwargs): ...
    def update(self, section_id, **kwargs) -> None: ...
    def delete(self, section_id) -> None: ...
    def move(self, section_id, project_id) -> None: ...
    def archive(self, section_id, **kwargs) -> None: ...
    def unarchive(self, section_id) -> None: ...
    def reorder(self, sections) -> None: ...
    def get(self, section_id): ...
