[tool.poetry]
name = "agal"
version = "0.0.1"
description = ""
authors = ["Gongziting Tech Ltd."]
license = "MIT"

[tool.poetry.scripts]
agal-cli = 'agal.cli:main'
agal-server = 'agal.server:main'

[tool.poetry.dependencies]
python = "^3.7"
websockets = "^10.1"
cryptography = "^3.4.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
