[tool.poetry]
name = "dg_face_parsing"
version = "0.0.5"
description = "Face parsing tools with BiSeNet"
authors = ["DataGrid"]
license = "MIT"
readme = "README.md"
packages = [ 
    { include = "face_parsing", from='src'}
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
requests = "^2.26.0"
tqdm = "^4.62.3"
numpy = "^1.21.4"
Pillow = "^8.4.0"
opencv-python = "^4.5.4"
torch = "^1.10.0"
torchaudio = "^0.10.0"
torchvision = "^0.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"